### ISSUE TITLE
Code exampels to work with wp-appkit

### ISSUE THREAD

**Issue by foxpcteam** [uncatcrea/wp-appkit#105]
Hi,
as i said before great project!

can you add more example how to work with:

1. get custom meta user (based on loged in users) to show in APP
update user meta from APP

2. get parameters from theme customizer?
update back some field in theme customizer

3. get data from plugins that using custom post types like woocommerce and etc... (like total sales and etc...)
or other plugins that use custom meta fields

update data from APP include meta fields and etc...

Thanks

**Comment by lpointet** [comment]
Hi,

First, thank you for testing and using WP-AppKit, great to hear that you like it.

Regarding code examples, we are actively maintaining our documentation that you can find here: http://uncategorized-creations.com/wp-appkit/doc/
It will guide you through the basics (and more) of an app creation.

Plus, please feel free to navigate through our blog, especially the following post that could be interesting regarding your suggestions: http://uncategorized-creations.com/1712/display-wordpress-custom-fields-app/

Finally, user login and related features are pretty new to WP-AppKit (even not released at the time), so fresh doc will come soon about that.

We will surely post new examples and documentation as the project grows, so don't hesitate to come back regularly :).

Best regards,
UncatCrea
