### ISSUE TITLE
Better support for splashscreens

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#107]
Currently we don't include by default the *Splashcreen* Cordova plugin and we don't do anything particular regarding splashscreens duration, display...

However, there's an attempt to manage the splashscreen display in *https://github.com/uncatcrea/wp-appkit/blob/b83ba15469529d47084624cd0578926637171a77/wp-appkit/app/core/phonegap/utils.js#L15*.

This attempt doesn't work unless user voluntarily include the *Splashscreen* plugin and add proper configuration in *config.xml*.

This is also why we have the **white screen bug on iOS** (ie. a white screen just after the splashscreen hides and before the app's UI shows up).

We should also support **fullscreen splascreens on iOS** (ie. no status bar).

I propose that we handle that by default in our export.

That means:
* Automatically add `<gap:plugin name="cordova-plugin-splashscreen" source="npm"/>` to *config.xml*
* For **iOS**, add the following preferences to *config.xml*:
  * `<preference name="auto-hide-splash-screen" value="false" />`
  * `<preference name="AutoHideSplashScreen" value="false" />`
  * `<preference name="FadeSplashScreen" value="true" />`
  * `<preference name="fade-splash-screen-duration" value="5" />`
  * `<preference name="show-splash-screen-spinner" value="false" />`
* for **Android**, add the following preferences:
  * `<preference name="SplashScreenDelay" value="10000"/>`
 
For iOS we also need to modify the `plist`file to hide the status bar while the splashscreen is visible. For that, we have to include the following lines in *config.xml*:
```
<gap:config-file platform="ios" parent="UIStatusBarHidden"><true/></gap:config-file>
<gap:config-file platform="ios" parent="UIViewControllerBasedStatusBarAppearance"><false/></gap:config-file>
```
*Please note that this syntax is only valid for PhoneGap Build.*

Along with *config.xml*, we have to modify *utils.js*.

For **iOS**:
```
setTimeout(function() {
    navigator.splashscreen.hide();
    StatusBar.show(); // Status bar is initially hidden, we need to show it when splashscreen disappears
}, 2000);
```

For **Android**:
`
navigator.splashscreen.hide();
`

In order to do that, I believe, we should also include by default the *Device* Cordova plugin and use it to detect iOS vs Android.

It is done by adding `<gap:plugin name="org.apache.cordova.device" />` in *config.xml*.

Doc is here: https://github.com/apache/cordova-plugin-device/blob/c6e23d8a61793c263443794d66d40723b4d04377/doc/index.md

EDIT on the 02/12/2015: added iOS fullscreen support.

**Comment by mleroi** [comment]
Hi @blupu, concerning the ios version of splashsreen.hide() : 
<pre>setTimeout(function() {
    navigator.splashscreen.hide();
    StatusBar.show(); 
}, 2000);</pre>
what is the goal of the delay introduced by setTimeout() here ? is it a kind of "don't ask me why but it has to be done this way" hack ;) ?
especially 2 seconds seems a bit long because it means that when the app finishes loading it waits systematically 2 seconds before closing the splashscreen.
Do you think we can we put a shorter delay (or remove it?)

Thanks!

**Comment by mleroi** [comment]
Implemented on development branch.
_cordova-plugin-splashscreen_ (with corresponding preferences according to platform) and _cordova-plugin-device_ are now added by default.
I didn't use any setTimeout() for now.
Tested a compilation on iOS device: it works fine, splashscreen hides gracefully :)

**Comment by blupu** [comment]
OK... Things have changed since I've opened that issue :-1: (I've read again the doc (here)[https://github.com/apache/cordova-plugin-splashscreen].) So I have retested all tags on both platforms.

**For iOS**

_config.xml_
```xml
<preference name="AutoHideSplashScreen" value="false" />
<preference name="ShowSplashScreenSpinner" value="false"/>
<gap:config-file platform="ios" parent="UIStatusBarHidden"><true/></gap:config-file>
<gap:config-file platform="ios" parent="UIViewControllerBasedStatusBarAppearance"><false/></gap:config-file>
```

_For the record: I have not been able to make fading work when autohide is set to false._

**For Android**

_config.xml_
```xml
<preference name="SplashScreen" value="splash" /> <!-- If you don't use this tag, be sure to have a splash.9.png image at the root -->
<preference name="SplashScreenDelay" value="10000" />
```

_For the record: auto hiding doesn't work on Android (https://issues.apache.org/jira/browse/CB-8396). So the plan is to have a very long delay for the splashscreen and let Javascript hiding the splashscreen._

Regarding setTimeout, I don't clearly recall why I had it :-( Anyway, it doens't seem to be useful now.

**Comment by mleroi** [comment]
Settings updated.
I've copied your "for the record" notes as comments in the code, so that we keep track of our choices on the matter.
I let you check if this is ok and I think we can close :)

**Comment by mleroi** [comment]
@blupu I think we can close this one?
