### ISSUE TITLE
Support for the Whitelist Cordova plugin

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#109]
This is an issue to bring support to whitelisting in WP-AppKit. We should discuss this subject here. Doc is there: https://github.com/apache/cordova-plugin-whitelist.

**Comment by lpointet** [comment]
As I said, I think we should:
 - include the whitelist plugin by default:
```
<gap:plugin name="cordova-plugin-whitelist" source="npm" />
```
 - allow WordPress domain and all subdomains:
```
<access origin="*.[host]" />
```
 - let the user add some patterns in WordPress panel to allow the corresponding URLs
 - see what should be done with "allow-navigation" tags

**Comment by blupu** [comment]
* So @lpointet you're talking of *Network Request* whitelist?
* I am wondering what does that mean: _This [intent] whitelist does not apply to plugins_ (?) Does that apply to inapp browsers?
* To be noted that you have to explicitly declare pseudo-protocols (such as geo://)

**Comment by lpointet** [comment]
- Yes, I'm talking about _Network Request_ whitelist.
 - I think they want to say that a plugin that will _natively_ create an intent will be able to do it, but a JS / HTML link won't. This means that a link handled by the inapp browser plugin needs a whitelist. We should test it IMO.
 - Yep, you can see that like a regex: *://xxx will allow any protocol with the xxx URL.

**Comment by blupu** [comment]
@lpointet I am confused as InApp browser works nicely in my demo apps. If I look at the .ipa config.xml, I see that PGB adds `<access origin="*" />` automatically :-\

**Comment by blupu** [comment]
OK Got it, issues are raised when using CLI 5.1.1 https://c.getsatisfaction.com/nitobi/topics/latest-phonegap-version-cli-5-1-1-breaks-all-external-json-calls.
* Note that using CLI 5.1.1 seems to require a preference
* Using CLI 5.1.1 seems to require to switch to NPM for Cordova plugins

**Comment by lpointet** [comment]
I'm always using the last version, which currently is "cli-5.1.1". Which one were you using?

**Comment by blupu** [comment]
My version field is empty and PGB *chooses* for me 3.70 :-\

**Comment by mleroi** [comment]
Whitelist Cordova plugin requires cordova-iOS 4.0.0.
For now PhoneGap Build only supports cordova-iOS 3.9.1.
So for now we add whitelist plugin only for android.
>**We have to remember to activate the whitelist plugin as soon as PHB supports cordova-iOS 4.0.0**
