### ISSUE TITLE
Status bar config. is done after the layout is drawn

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#11]
It appears that when using the StatusBar PhoneGap plugin, the status bar configuration is done after the splashscreen is hidden. Ideally, we should have a way to hook as early as possible (i.e. before the layout is done).

**Comment by lpointet** [comment]
@blupu is this issue still relevant?

**Comment by lpointet** [comment]
@blupu ping :)

**Comment by uncatcrea** [comment]
It is not.
