### ISSUE TITLE
Maintaining/Updating WP AppKit

### ISSUE THREAD

**Issue by spwebguy** [uncatcrea/wp-appkit#114]
Hi there,

This is not really an issue (sorry for that). I'm not a GitHub expert and I would like to know if this plugin/framework is **currently maintained by its authors**. 

I completely love the idea and would like to use *WP AppKit* for an app I'm building but I would like to make sure that this is not an "abandoned" project.

Thank you for the **GREAT** work.

**Comment by blupu** [comment]
![giphy](https://cloud.githubusercontent.com/assets/6179747/10320831/bf411e54-6c75-11e5-98a2-f47c877e0056.gif)

OK, this one was easy :-) Yes, WP-AppKit is currently maintained and is not going anywhere.

**Comment by spwebguy** [comment]
![giphy](https://cloud.githubusercontent.com/assets/8936613/10328267/23353724-6cd0-11e5-8e33-38f2877c04c2.gif)

Well, great then. Thanks a lot.
