### ISSUE TITLE
Custom components and Lists output

### ISSUE THREAD

**Issue by spwebguy** [uncatcrea/wp-appkit#118]
Hi there,

*Please, if this is too basic, or too much to answer, just let me know and I'll stop asking. You're probably working on the framework and the documentation anyway.*

I'm building an app with multiple custom templates (home.html, discover.html etc...). I have custom post types like "books", "movies", all with post meta data ("author", "number of pages" etc...).

I would like to know how to create my queries (the same way I usually do it with PHP, with stuff like "cat", "number of posts to retrieve", "sorting by term" etc...), send it to the app and output it correctly using the _s' syntax.

While I understand all this, I can't seem to make it work. It probably is very simple since I don't see anybody asking for this. I tried looking at the code on GitHub. I also read the docs several times. I'm able to create a component and fetch a list of any post type, but I can't do anything with it (sorting, get post meta data etc...), I'm not able to "call" the component on a specific template. I tried adding functions to a separate plugin (I'm a plugin developer) but can't seem to be able to send something to the app and retrieve it.

**So here is what I'd like to do for example: Get all the "books" (CPT) in "thriller" (custom tax) and sort them by "number_of_page" (custom post meta — int).** If you have time and this is not too much work for you, I would like to know **what should be added to the functions.php** (or custom plugin) on the WordPress side, in **the component settings** (WP AppKit — App edit screen) and in **the custom template** (let's say home.html).

I don't need something that I'll just have to copy-paste. My app doesn't even have a "book" CPT, I would just like to have a working example of this so I can get started. I tried looking at the themes, couldn't see this anywhere.

**Thank you so much** in advance if you can do that (no need to spend much time on this, I would just need some "hints").

Gia

**Comment by mleroi** [comment]
Hi, you can do this 2 ways : 
- customize the WP query of your "post list" component using the "wpak_posts_list_query_args" hook in functions.php, a custom plugin of yours or in your theme's php directory (http://uncategorized-creations.com/1062/php-folder-wp-appkit-theme/) : http://uncategorized-creations.com/wp-appkit/doc/#1678-wpak_posts_list_query_args. Ok this is really not well documented yet, you can also search for "wpak_posts_list_query_args" in the source code to see how it works. I can send you a usage example when I have more time if needed. 
You can do a lot of customization using this hook (you may want to take a look at https://codex.wordpress.org/Class_Reference/WP_Query to see all you can do).
- If your query is really specific you can also make your own custom component : http://uncategorized-creations.com/wp-appkit/doc/#1638-components.

Hope this helps, don't hesitate if this is not clear, I'll send you a real example.

**Comment by mleroi** [comment]
Regarding post metas you may want to take a look at http://uncategorized-creations.com/1712/display-wordpress-custom-fields-app/

**Comment by mleroi** [comment]
Here is an example of component query customization : 
https://gist.github.com/uncatcrea/c4489844129ad86ffa9f

About retrieving components data from custom templates, you can see : 
https://gist.github.com/uncatcrea/02c59fb187eecf8e58e7

Hope this helps. Don't hesitate for any other questions.

**Comment by spwebguy** [comment]
Hi, **thank you** very much for all this. It's really helping. I managed to get all my "custom loops" working, retrieve the content in my app and display it correctly. Your snippets are well documented and easy to implement. This is going to help many others in the future.

I have **other questions/issues** for you. It's still beginner stuff, but I think it's very good that you have a couple of Gists like this, I sure won't be the only one using them.

You said "don't hesitate for any other questions" so I'll go ahead and ask more stuff. I will start a new issue so it's easy for others to find this info in the future. This one can be closed, the answer is very good. 

Thanks again for everything.

Gia
