### ISSUE TITLE
Component/Screen/Template navigation

### ISSUE THREAD

**Issue by spwebguy** [uncatcrea/wp-appkit#119]
Hi,

This might sound silly, I'm not too familiar with how apps are built (I'm talking about the component system). If I understand well, in a standard app it's pretty much one component per screen. Most of the time you'll have a list, then an item (single.html), then comments inside that item.

Now, what if I want to have special pages? Let's say that I want to have a **homepage** (the first page showing when you open the app). I want this page to show the *most popular books*, the *recently added books* and some highlighted stuff. 

I managed to build a **home.html** template and get the content to show inside. I used one component per "loop", I filtered them with functions.php (or anything else) and displayed them using TemplateTags.getComponent('my-component'). So basically I have: **TemplateTags.getComponent('mostpopular')**, **TemplateTags.getComponent('rencentlyadded')** etc... 

What I'm having issues with is how to *articulate* all this. I'm not sure how to **define what's going to show first** on app launch (not talking about first launch). I have lists, singles and everything that a standard app would have, but I'm having issues with the nav.

I think I'm trying to reproduce the same thing as in a website, which is not good. Like changing from page to page when it should probably be from component to component. Could you **briefly explain how this component/screen/template system works**? Doesn't have to be with code examples. It's just that for website people all this is pretty new.

If you let me I'll just have dozens of HTML templates at the root, which I belive is **not** the way to go.

Thanks in advance for your help! 

Also wanted to ask you guys, is there any way I can help you? Obviously I can't contribute with the code but I'm a UI/UX guy, I can do web design. Do you have a donate button somewhere? I really would like to show support, this project is worth it.

Gia

**Comment by blupu** [comment]
This is not silly at all. It is very common to have specific pages launched at app start (or first launch) such as small tutorial or invitation to update the app.

You found the one way to do it: create a custom component and have it in position 1 in your menu.

You may also handle the default page to be displayed at app launch with JavaScript. You're about to discover the magic world of *routes* but I'll let @mleroi write about them.

**We're totally commited to help our users, so don't worry about asking any questions you may have.** However, we may have some delay in our answers when the load is high.

Regarding your help proposition, you're more than welcomed! We may exchange about that on Slack if it suits you?

**Comment by spwebguy** [comment]
Hi, different timezones indeed! I live and work in Shenzhen, China (near Hong Kong). Today I built a small app with your framework. I used **PhoneGap Build** because I'm not too comfortable with the command line. I must say WP AppKit is super stable and super fast (really). The app's working perfectly (it's not finished but I'm getting there!).

I asked these questions because I know that building a website and an app aren't the same things. I'm trying to avoid dirty fixes and unstable workarounds... I want to build it the way it's supposed to be built. Also, whenever I ask something I'll be careful when choosing the words in the subject, so others can easily find it.

Take your time! No rush.

I'm not a GitHub expert, I don't know if I can send you my email like this or if there's a better way to do it. I'm already thinking about a couple of things I *could* help with (always up to you of course).

Thank you so much for this framework, and thanks for your answers, it's awesome.

Gia

**Comment by mleroi** [comment]
Hi Gia,

As @blupu said, the questions you're asking are about Routing and Navigation in apps : following your feedback we just updated/completed our doc concerning those important notions :
- <a href="http://uncategorized-creations.com/wp-appkit/doc/#1439-navigation">Navigation</a>
- <a href="http://uncategorized-creations.com/wp-appkit/doc/#1587-routing">Routing</a>

This doc is a work in progress and questions like yours are good occasions for us to see what's missing ;)

To define what's showing on app launch you'll use the <a href="http://uncategorized-creations.com/wp-appkit/doc/#1580-launch-route">"launch-route" filter</a> (certainly along with the <a href="http://uncategorized-creations.com/wp-appkit/doc/#1588-refresh-at-app-launch">refresh-at-app-launch</a> parameter) or the <a href="http://uncategorized-creations.com/wp-appkit/doc/#1595-default-route">"default-route" filter</a>. Be sure to note the difference between those two "launch-route" and "default-route" :)
Doing this you'll probably end up with something like (in functions.js) : 
<pre>
//Use of "launch-route" (allows to reserve "default-route" for "after refresh" usage) : 

App.setParam( 'refresh-at-app-launch', false );

App.addCustomRoute( 'my-home-route', 'my-home-template' ); 

App.filter( 'launch-route', function( launch_route, stats ) {
    return 'my-home-route';
} );
</pre>
Or just :
<pre>
// Use of "default-route" (by default, "launch-route" takes the value of "default-route").
// This is if you don't need to differentiate your "launch route" from your "default route"

App.addCustomRoute( 'my-home-route', 'my-home-template' ); 

App.filter( 'default-route', function( launch_route, stats ) {
    return 'my-home-route';
} );
</pre>
depending on what you want to achieve.

Making a really custom navigation among your app is possible (using get*Link() template tags, manual fragments, or App.navigate() as explained in the Navigation section of the doc). However navigation is also linked to app <a href="http://uncategorized-creations.com/wp-appkit/doc/#263-history">History</a> (what allows to implement the "Back button" functionnality). If you don't break the default List > Single > Comments navigation logic you should not have to worry about it though. But just so you know, if you need to customize this default History management for your specific navigation needs, it is possible too, just not documented yet! Feel free to ask for it if needed.

It's so true that building an app is different than building a website. And that's true for so many aspects of app development and design. 
Regarding navigation and routing in WP-AppKit apps, in a nutshell, once you replaced "url" by "fragment" and "rewrite rules" by "routing", and you know how to play with default/launch routes and building screen fragments, you're pretty good to go :)

As Benjamin said, you're more than welcome if you want to contribute to the UI/UX part of our project!

**Comment by spwebguy** [comment]
Hi, that's really helping, thanks a lot! I wrote to you guys about the UI/UX.

I might have a couple of more questions for you later if you have time of course. I'll ask them here on GitHub (splashscreens, transitions etc...). I'll take some time to look for answers myself before I come here bothering you haha!

Until then, good luck with all this! It's a very interesting and exciting project.
