### ISSUE TITLE
html code tables

### ISSUE THREAD

**Issue by kinti** [uncatcrea/wp-appkit#120]
code [table][tr][td] is ignored..., where? why? thanks!!!!

**Comment by blupu** [comment]
Hi, could you detail what you're trying to achieve and what is the problem you encounter?

**Comment by kinti** [comment]
i'm posting data in table in wp, but the table code is ignored in app, only table codes, headers, p's, and li's, are allowed....,

**Comment by blupu** [comment]
Unfortunatly, you're right. HTML tables are stripped from what the web services return. We're going to fix that in the next WP-AppKit version.

In the meantime, you can create a *.php* file in your theme's *php* folder and hook with the following code to specifically allow HTML tables.

```php
function my_theme_allow_tables( $allowed_tags ) {
    $allowed_tags .= '<table><tr><td><thead><tbody><tfoot>';
    return $allowed_tags;
}
add_filter( 'wpak_post_content_allowed_tags', 'my_theme_allow_tables' );
```

**Comment by kinti** [comment]
thanks!

**Comment by kinti** [comment]
[inputs, forms] too
