### ISSUE TITLE
Facebook/Twitter login

### ISSUE THREAD

**Issue by spwebguy** [uncatcrea/wp-appkit#121]
Hi guys,

Still working on my little app (based on **WP AppKit**). It's going really well, I'm done with the navigation and all the pages pretty much. I'm now working on everything that's "user" related, starting with the authentication!

I'd like to have **Facebook/Twitter and mail sign in/up** and I have no idea where to start. Here is a very vague question (any answer will be much appreciated):

**How should I approach Social/mail sign in/up? What are good things to read/do in order to achieve this?**

Thanks a lot for this framework, I'll never say it enough, it's great.

Gia —

**Comment by blupu** [comment]
Hi, good to hear that your project is in good shape :-) Regarding, social login, there's numerous Cordova plugin and JS librairies to achieve this. below, some thoughts about that:
* The easiest way is probably to use a JS library. However, you'l have to check how it goes with the in app browser
* Remember that iOS has the ability to register Facebook and Twitter accounts at the OS level - if you want to access them, you'll need a Cordova plugin
* At last, it's one thing to log with a social account, but if you want to register your user in WordPress, it will add a layer of complexity (Here's an article about that http://www.raymondcamden.com/2015/07/10/combining-client-side-social-login-and-server-side-authorization-with-cordova-and-node)

**Could you describe a bit more what you want to achieve?**

*I think we'll have to do some research to find the right solution*

**Comment by spwebguy** [comment]
I'll use the support email to continue this discussion. Thanks a lot for helping me :)

Gia —

**Comment by blupu** [comment]
Great! Closing the issue.
