### ISSUE TITLE
a section to add content only in webapp?

### ISSUE THREAD

**Issue by kinti** [uncatcrea/wp-appkit#123]
in a post, a new section to add content only in webapp...., 
if this field is empty, shows the post content, if we put content in this new field, only this content appears in webapp, 

an idea, because i have a post with form, and form not run, then, i will put the same content without the form....

there are a plugin that do something like, https://wordpress.org/plugins/wp-mobile-detect/faq/,  but crashes connection between wp an webapp

**Comment by blupu** [comment]
Hi, I believe that you should simply allow forms as you did for HTML tables (#120).

**Comment by kinti** [comment]
no exactly because the "action" of the form prevent send it, at least in "contact form 7"....,

**Comment by blupu** [comment]
OK. Didn't understood that you want to use a form already on the site. My advice: use an in app browser.
