### ISSUE TITLE
Tell Me More links

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#135]
Working on help texts, I found that we should have short help texts with the possibility to add a *Tell Me More* link at the end (pointing to an online help? Displayed a bigger tooltip?).

What do you think?

**Comment by lpointet** [comment]
I think it's a good idea to point out our online documentation. However, display a bigger tooltip seems a bit too much to me. The help is already hidden by default indeed, so having 2 levels of hidden texts would be unefficient I think.
_Tell me more_ links will be displayed within help texts, so I propose to close this issue and continue discussion in #57.
