### ISSUE TITLE
Include a demo theme in default WP-AppKit plugin package

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#152]
Install a default app theme at plugin installation.

**Comment by lpointet** [comment]
Some thoughts about TODO:
* Implement [Filesystem API](https://codex.wordpress.org/Filesystem_API) instead of dealing with PHP functions directly
* Use "direct" filesystem access type at activation if possible, or prompt an admin notice to run the copy manually (requesting credentials)
* What should be done while WP-AppKit is upgraded?
    * What if the themes folder already exist, but not themes folders inside it? => my proposition is to notify the user and let him choose if we should copy these default themes or not (storing the choice if "no"), maybe for each theme independantly?
    * What if a new version of the default themes is embedded compared to the already installed ones? => my proposition is to notify and let the choice as well, maybe for each theme independantly?

**Comment by lpointet** [comment]
See CLI export for developments about unzip.

**Comment by lpointet** [comment]
About default themes names/slugs discussion, here is what I found out about WordPress Core itself:
* If you rename a default theme (inside style.css header), it's still detected as default theme
* If you move a default theme (change folder's name):
    * Theme's name is automatically suffixed by the folder's name, ex: Twenty Ten/twentytencopy
    * Upgrade is deactivated
* If you move *and* rename a default theme, it's a brand new theme, not a default one anymore

The main thing is that the only data counting for a theme upgrade is its slug, which actually is its folder's name (ex: twentyten). The name is only checked for convenience and display, in case you duplicated it.

That being said, the main difference for us is that for default themes, we won't check for new versions online.

**Comment by lpointet** [comment]
Commit one default theme.
