### ISSUE TITLE
Add timezone offset to config.js

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#158]
When displaying time diffs like "X time ago" we need to be able to compute the gmt time out of the local time sent in web services.
Adding the timezone offset (from the WordPress core option "gmt_offset") to config.js will allow to do that.

**Comment by Ices-Eyes** [comment]
Hi. By using this method leads to wrong times when clock change to or from daylight savings time... IMHO, it would be better to ask to server the difference for the time when app start, or you have to release an update of the app at every time change...

**Comment by mleroi** [comment]
Hi @Ices-Eyes, this is a good point, we should probably pass the offset in the synchronization web service so that it can be updated regularly.

**Comment by blupu** [comment]
Good point indeed. However, some users already relies on that functionality. So we should maintain it. Another thing is that is has to be available online, so we have to store it in the local storage (?).

**Comment by Ices-Eyes** [comment]
Hi. This was schedule for 1.5.2. Has this been fixed in some way now that the version is out? :)

**Comment by mleroi** [comment]
Hi @Ices-Eyes sorry we could not do it for 1.5.2. We'll do our best to get it ready for 1.5.3.
Regards,

**Comment by Ices-Eyes** [comment]
Hi. No problem, not seen it on the changelog, and wondering if it was there ;)Keep on with the good work! :+1:
