### ISSUE TITLE
Post data into comment:posted info event

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#163]
Currently, 'comment:posted' event sends comment data as argument and the total list of comments for the corresponding post.
But there is no data about the given post (id, slug, title, etc.). I think it may be good to get some information about this post within this event.

**Comment by mleroi** [comment]
@lpointet I think we can merge this, if the post id is enough for your need (I guess you do some kind of getItem(post_id) to get more info on the post in your function?)

**Comment by lpointet** [comment]
@mleroi Yep, post id is enough for my need, and I was thinking using getItem or something equivalent of any other needs.

**Comment by mleroi** [comment]
Merged into development :)
