### ISSUE TITLE
Add WP Network specific htaccess rules automatically at WP-AppKit installation

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#167]
WP-AppKit apps preview requires specific additional htaccess rewrite rules to work on WP Network.
We should add those rules automatically to htaccess.

**Comment by lpointet** [comment]
WordPress is supporting IIS web server, I guess we should try and support it as well.

**Comment by mleroi** [comment]
@lpointet Good point. Maybe I'll first address the Apache part for 0.5, and open a new issue for IIS and Nginx.

**Comment by mleroi** [comment]
I pushed a first version of this on feature_167.

We can't use the "mod_rewrite_rules" on WP Networks (where WP htaccess rewrite rules have to be copied by hand at the end of Network install process, so this hook is not triggered).
So I add our WPAK rules at the beginning of htaccess by writing directly to the file at WP-AppKit install.

There's still an issue I want to address: 
When we deactivate WP-AppKit we want to remove our rules from htaccess. But before removing them we have to check that the plugin is deactivated on ALL network's sites... If WP-AppKit is still installed on at least one site, we have to keep the rules.

**Comment by mleroi** [comment]
Following @lpointet's feedback (https://github.com/uncatcrea/wp-appkit/commit/30ada039be635addc86aba2409a03dd77f0be772#commitcomment-16169791), use:
```
$slashed_home      = trailingslashit( get_option( 'home' ) );
$base              = parse_url( $slashed_home, PHP_URL_PATH );
$document_root_fix = str_replace( '\\', '/', realpath( $_SERVER['DOCUMENT_ROOT'] ) );
$abspath_fix       = str_replace( '\\', '/', ABSPATH );
$home_path         = 0 === strpos( $abspath_fix, $document_root_fix ) ? $document_root_fix . $base : get_home_path();
```
instead of get_home_path()

**Comment by mleroi** [comment]
Handled htaccess rewrite rules removal on Network wide plugin deactivation, and used the above hack concerning home_path retrieval.
