### ISSUE TITLE
Create a ThemeApp.navigateToPreviousScreen() function

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#168]
Handle back button navigation via a new ThemeApp.navigateToPreviousScreen() function and remove current ThemeApp helpers setAutoBackButton() and updateBackButtonEvents() because we have to let themes do their own bindings for back button.

ThemeApp.navigateToPreviousScreen() will trigger a "navigate-to-previous-screen" event that'll allow to track back button actions.

Note that Bootstrap themes will have to be updated after that to use the new back button logic instead of the old one.

**Comment by lpointet** [comment]
@mleroi just a thought about my commit: the event is named "navigate-to-previous-screen" without any namespace, unlike most of the others like "refresh:start" (namespace = refresh). Should we add one maybe?

**Comment by mleroi** [comment]
@lpointet I suggest "navigate:previous-screen" if ok with you, as detailed here https://github.com/uncatcrea/wp-appkit/commit/1b5f48cb83175d97c9d5d184b54e76dc2b8d6aea#commitcomment-16063331

**Comment by lpointet** [comment]
@mleroi I'm OK, here it is ;).

**Comment by mleroi** [comment]
Cool thanks! :) 
(and I'm making the update on Bootstrap theme side)
