### ISSUE TITLE
Trigger a "component:get-more" info event in App.getMoreOfComponent()

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#169]

**Comment by lpointet** [comment]
@mleroi I let you check my commit to see if it's OK with you before merging into development branch ;).

**Comment by mleroi** [comment]
@lpointet I was thinking I'd do this by passing the cb_ok() callback to triggerInfo(), because it's better when we can try to homogenize args of callbacks that are made along with info events.

This would give:
```
app.triggerInfo( 'component:get-more', { new_items: new_items, is_last: is_last, nb_left: nb_left, new_ids: new_ids, global: global, component: component }, cb_ok );
```

This "just" means that we have to update the App.getMoreOfComponent() success callback used in ThemeApp.getMoreComponentItems() and we should be good to go.

Tell me what you think, I can do it if you want :)

**Comment by lpointet** [comment]
@mleroi I asked myself if I should do that or not, but I was thinking consequences would be much more painful than that :).

**Comment by mleroi** [comment]
Cool! I just merged this :)
