### ISSUE TITLE
Bug in InAppBrowser 1.0.1

### ISSUE THREAD

**Issue by anveshnara** [uncatcrea/wp-appkit#170]
I am using InAppBrowser 1.0.1, I am using cordova.InAppBrowser.open() method I am passing Url from Mojioclient OAUTH 2.0 when I was launching My application Mojio Login page workings in Mobile browser and InAppBrowser but mobile browser overlapped InAppBrowser. Is there Any Issue with Version 1.01.

**Comment by uncatcrea** [comment]
Hi, sorry but we don't have any skills regading compatibilities between InAppBrowser and MojioClient.

**Comment by anveshnara** [comment]
Thanks Now its is working good for me .
