### ISSUE TITLE
Config.xml plugin declarations

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#172]
According to the following doc, `<gap:plugin>` notation is now deprecated and `<plugin>` should be used instead.

**Comment by lpointet** [comment]
Plus, `version` attribute is now renamed `spec`.

**Comment by mleroi** [comment]
"The following doc : http://docs.build.phonegap.com/en_US/configuring_plugins.md.html#Plugins

**Comment by lpointet** [comment]
A file to test many cases for this Plugins field is available here: https://gist.github.com/lpointet/338f96715f6bee85fda6

@mleroi One question I have: do we update WP-AppKit code and especially array key to be `spec` instead of `version` to reflect PhoneGap Build change? This would break backward compatibility.

**Comment by mleroi** [comment]
@lpointet I'm not sure I see all implications. If we change all our "version" keys to "spec" are we not ok?
I possibly see a problem with "wpak_default_phonegap_build_plugins" filter if someone was using it adding a plugin with "version" key. Do you see other backward compat problem?

**Comment by lpointet** [comment]
@mleroi That's it, those using this filter to add some more plugins (e.g. addons) won't get their version anymore. This is the only implication :).

**Comment by mleroi** [comment]
@lpointet Ok. So if ok with you I think we can consider it a minor implication, also considering we're still in beta (and this is not our fault, but PhoneGap's fault :p). 
We just have to keep track of those small backward compatibility issues and inform people in some way about them when we make the 0.5 release.

**Comment by lpointet** [comment]
@mleroi agreed, I'll update code.
