### ISSUE TITLE
Default embedded Android splashscreen raises error in Phonegap Build

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#173]
When trying to build on PHB with our default Android splashscreens, the build fails returning the following error:
"Error - A 9-patch image in your assets is malformed: splash.9.png"

PHB logs:
"ERROR: 9-patch image /project/res/drawable-hdpi/splash.9.png malformed. Must have one-pixel frame that is either transparent or white."

**Comment by blupu** [comment]
The bug only occurs when compiling with Gradle. As explained in the article below, Gradle verifies the 9 patchs images and it appears that current embbeded 9 patches are not correct.

http://phonegap.com/blog/2015/09/28/android-using-gradle/

I've recreated all Android splashscreens and made a successful Gradle compilation. Il will drop them in the _Issues_ Slack channel.

**Comment by mleroi** [comment]
\o/ Just made a build test with gradle with those new icons, it works like a charm
