### ISSUE TITLE
Translation : include texts

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#175]
In the file "theme-bo-settings.php" (https://github.com/uncatcrea/wp-appkit/blob/development/wp-appkit/lib/themes/themes-bo-settings.php#L71), we are displaying a text including the required version. We should include this version into the translatable text via a "%s" sprintf parameter. Indeed, some languages may want to put this version name at another place in the sentence.

Same thing here:
- https://github.com/uncatcrea/wp-appkit/blob/development/wp-appkit/lib/apps/apps.php#L379
- https://github.com/uncatcrea/wp-appkit/blob/development/wp-appkit/lib/apps/apps.php#L410

**Comment by lpointet** [comment]
@mleroi assigning you this issue before closing it, just for you to review/comment/update with some more improvements.

**Comment by mleroi** [comment]
Thanks @lpointet, seems perfect to me :)
