### ISSUE TITLE
Page screens : rename "item" to "post" (or "page") in current_screen.data

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#177]
To access the page object on JS side when displaying a page screen, currently we have to use current_screen.data.item. 
Would be more explicit to use current_screen.data.post (that would be coherent with single screen).

If we don't want to break backward compat, we could also let current_screen.data.item and create an alias current_screen.data.page, but it would certainly be more confusing than helping...

**Comment by mleroi** [comment]
We now have "current_screen.data.post" instead of "current_screen.data.item" for page screen.

I chose ".post" and not ".page" to stay consistent with page.html template where we use "post" object and not "page".

@lpointet I checked quickly in your addons and didn't find any usage of "current_screen.data.item" that could be broken by this commit, but maybe you can double check in case I missed something ;)

**Comment by lpointet** [comment]
@mleroi I confirm, nothing broken on my side :)
