### ISSUE TITLE
App permissions

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#181]
Currently, compiling a WP-AppKit app through PhoneGap Build without any specific option asks for a lot of permissions to be installed.
We should limit those permissions to what's really needed.

**Comment by lpointet** [comment]
tested with pushwoosh and google analytics addons and their corresponding cordova plugins, tested with a simple app and everything works as expected. By default, only network permission is requested.
@blupu @mleroi Could you test on your side, especially with iOS devices?

**Comment by blupu** [comment]
Not sure to get it correctly. What did you do exactly?

**Comment by lpointet** [comment]
I added a specific tag to remove all permissions asked by a build. It shouldn't mean that Cordova plugins don't work anymore because they can ask for specific permissions they need: that's typically what needs testing. That and themes.

**Comment by lpointet** [comment]
It seems `<feature>` tag is now deprecated: http://phonegap.com/blog/2016/02/24/phonegap-build-confg-xml-now-required-and-other-updates/
Let's remove the ability to add these then...
