### ISSUE TITLE
CrossWalk support

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#188]
Add the possibility to add CrossWalk support for Android apps.

**Comment by blupu** [comment]
**A quick note to add that we should propose to lock the Crosswalk version.** I had the habit to let the version empty (ie. compile with the latest) and my compilations broke yesterday as a new version of Crosswalk has been released (1.6.0) and is not currently supported by PGB. The advice from support was to lock my version to 1.5.0.

**Comment by lpointet** [comment]
As discussed, needed for the new default themes (to be shipped with 0.6).

**Comment by lpointet** [comment]
@blupu quick question: why not using it for iOS as well?

**Comment by blupu** [comment]
Essentially because it doesn't work with iOS, it's an Android only webview. On iOS, webview perf is related to the new iOS webview compatibility (http://devgirl.org/2014/11/10/boost-your-ios-8-mobile-app-performance-with-wkwebview/). But that's totally another story. I also think it's a lesser problem as we're addressing the infinite variations of the Android world and its slowness to update to last OS version.

**Comment by lpointet** [comment]
Well, it seems to work but you're right about WKWebView: https://crosswalk-project.org/documentation/ios/cordova_plugin_support.html
I was asking this to know if this field should be visible only with "Android" platform. What I understand is the answer is "Yes". :)

**Comment by lpointet** [comment]
After discussions and research:
* include Crosswalk plugin by default, with a filter to remove it
* plugin name (npm) is `cordova-plugin-crosswalk-webview`
* latest stable version is 1.7.0, not sure if tested yet, 1.6.0 works for sure
* provide a filter to change the included version

**Comment by lpointet** [comment]
After discussions and tests:
* CrossWalk versions 1.6.0, 1.6.1 and 1.7.0 don't work with PhoneGap Build, we should go back to 1.5.0 until it's fixed
* New filter to update CrossWalk version is not necessary, this is still possible thanks to `wpak_default_phonegap_build_plugins` filter
