### ISSUE TITLE
Add upgrade routines

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#193]
Related to #152. Indeed, 0.6 will need to run some update scripts on existing WP-AppKit installs:
* delete a transient

In future versions, we'll probably have to handle default themes upgrades, and other modifications we couldn't think of now.

Requirements:
* detect a version change: store the current version into the database, and check against a hardcoded version
* handle version upgrade for more than 1 version (e.g. 0.5 => 1.2), meaning each intermediate upgrade routine should run
* separate each routine to be able to run it independantly from the other ones
* add action(s) to allow third party plugins/themes to hook into a migration (e.g. WP-AppKit addons)

**Comment by mleroi** [comment]
Hi, the logic you implemented seems perfect to me and corresponds to all the upgrade requirement.
2 questions I'm asking myself regarding version format:
- of course I really love 42 as it is the key to the mysteries of the universe :D but is there a particular reason why we wouldn't use a 0.1.2 version format and compare it with PHP's version_compare ?
- and if we can do so, do you think we could use the plugin version directly (using get_plugin_data() ) or is there some cases where keeping a separate db version is required?

It's just that I feel it could be clearer to base those upgrade comparisons on plugin versions (as you named the upgrade function upgrade_060() ) than on a non related db version, but I'm not sure I see all implications.

**Comment by lpointet** [comment]
Great, thanks for reviewing!
Actually I firstly did what you propose, and then I looked at what WordPress is doing. They are using an integer for db versions, so I reused the same logic. I guess it's related to all intermediate versions (during development), but I'm not completely sure, and I tend to think that we could use the plugin version.

**Comment by lpointet** [comment]
As discussed, come back to plugin version to handle db version as well.
