### ISSUE TITLE
Fix argument names and order in 'screen-transition' action

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#197]
Currently, the 'screen-transition' action receives the following argument:
`$current, $next, current_screen, previous_screen`
We should make it:
`$current, $next, current_screen, next_screen`

This means we have to reverse the order of the corresponding arguments passed to doActions('screen-transition'):
replace `App.getCurrentScreenData(),App.getPreviousScreenMemoryData()` by `App.getPreviousScreenMemoryData(),App.getCurrentScreenData()`

This implies args order changes in `transition-direction` action and `ThemeApp.getTransitionDirection()` too.

**Comment by mleroi** [comment]
@blupu So, as discussed, screen transition argument names and order have changed in:
- 'screen-transition' action: now `$current, $next, current_screen, next_screen`
- 'ThemeApp.getTransitionDirection()' function: now `current_screen, next_screen`
- 'transition-direction' filter: now `current_screen, next_screen`
I hope you'll be able to update Q theme accordingly without too much headache, tell me if not ;)

I'll update the doc when releasing 0.6.

**Comment by blupu** [comment]
No headache at all but 10 min work :-) I've to say it is a lot more readable now.
