### ISSUE TITLE
Unused or misused events

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#203]
The 'screen:showed:failed' event can never be triggered in the current implementation. Remove it.

Also check the following unused events : 'menu:refresh',’header:render','waiting:start','waiting:stop'
and see if we keep/remove/rename/modify them.

**Comment by blupu** [comment]
Could you precise what are _menu:refresh_, _header:render_, _waiting:start_, _waiting:stop_ and when they're fired?

**Comment by mleroi** [comment]
- **menu:refresh**: triggered when the menu template has finished rendering. Useful to bind "undelegatable" JS events on menu's DOM (we had a usage example with jQuery mmenu lib for a user recently). Of course we can do this menu event binding in "app-ready", but I think it is useful to have a dedicated event for menu. I intend to rename this event *menu:rendered* and document it.

- **header:render**: it is linked to an old forgotten feature that allows to handle a dynamic header region (if _layout.html_ includes a `<% header %>` tag, it is rendered with a _header.html_ template). I think we can keep this event this way for now, just rename it *header:rendered*

- **waiting:start** and **waiting:stop**: this was an attempt of a general way to handle waiting feedback (eg spinners) while loading screens. But this is not used anymore. I will remove that, and we can always think of a good way to handle that if needed.

**Comment by blupu** [comment]
Clearly menu and header events are very interesting. As are waiting events BTW but I can surely implement such behavior in my themes without them. Thx.

**Comment by mleroi** [comment]
Waiting events is definitely something we could rethink about if we find it needed in themes. 
The way it was implemented here was not really usable because it didn't hook properly in app processes. 
We can totally discuss a good way to rebuild this kind of system if useful in themes.
