### ISSUE TITLE
Missing splashscreen fading delay

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#206]
The preference tag is missing for splashscreen fading delay in _config.xml_ for iOS. (By default, it is 3 sec and it's too slow to fade out.)

We should include:
```<preference name="FadeSplashScreenDuration" value="1000"/>```

See https://github.com/apache/cordova-plugin-splashscreen for reference.

**Comment by mleroi** [comment]
FadeSplashScreenDuration added.
So we now have:
```
<preference name="AutoHideSplashScreen" value="false"/>
<preference name="FadeSplashScreenDuration" value="1000"/>
<preference name="ShowSplashScreenSpinner" value="false"/>
```
@blupu do you confirm that we keep AutoHideSplashScreen to false ?

**Comment by blupu** [comment]
Yes we do as soon as the core hide the splashscreen of course.

2016-04-12 17:32 GMT+02:00 mleroi <notifications@github.com>:

> FadeSplashScreenDuration added.
> So we now have:
>
> <preference name="AutoHideSplashScreen" value="false"/>
> <preference name="FadeSplashScreenDuration" value="1000"/>
> <preference name="ShowSplashScreenSpinner" value="false"/>
>
> @blupu <https://github.com/blupu> do you confirm that we keep
> AutoHideSplashScreen to false ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/uncatcrea/wp-appkit/issues/206#issuecomment-208963445>
>



-- 
Benjamin Lupu
Email: benjamin.lupu@gmail.com

**Comment by mleroi** [comment]
Ok thanks :)
