### ISSUE TITLE
Add WordPress url in config.js

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#207]
It can be useful for themes to have the WordPress site url available to open WordPress links directly in app.
We should add a `wp_url` entry to config.js

**Comment by mleroi** [comment]
`Config.wp_url` is now available in app

**Comment by xanxion** [comment]
i can't seem to find this config.js file anywhere, and i cant link to other posts in the app.
Can anyone point me in the right direction?

**Comment by xanxion** [comment]
Its seems like its using an in app browser, but i get the following error:
functions.js?wpak_app_id=spiloghygge&bust=1481101731885:755 Uncaught TypeError: Cannot read property 'href' of undefined
    at HTMLAnchorElement.openInBrowser 

But, what i want is just going to another post in the app, internally.

**Comment by lpointet** [comment]
Hi @xanxion and thanks for using WP-AppKit.
You might want to check out this post on our website: http://uncategorized-creations.com/2287/navigation-and-routing-in-wp-appkit-apps/
Especially the "Do App Screens Have Corresponding URLs?" part.

**Comment by mleroi** [comment]
Hi @xanxion, 
Also if you're using Q Themes and your internal link still opens with inAppBrowser, you can use the following trick: https://github.com/uncatcrea/q-android/issues/6 (which should be fixed in next Q Themes version.
