### ISSUE TITLE
Export for cordova

### ISSUE THREAD

**Issue by gerhardsletten** [uncatcrea/wp-appkit#212]
It is pretty easy to convert the export to use with cordova, but one would need to do some manual adjustments in the config.xml, but this could be done with an export button for cordova beside the phonegap build. Think that would increase the adoption rate, since most people use cordova/phonegap library locally.

**Comment by mleroi** [comment]
Hi, 
We have a Cordova/Phonegap CLI export that is available when using our "WP CLI" export. The doc about it is here: http://uncategorized-creations.com/wp-appkit/doc/#2213-wp-cli-export

We may indeed add this CLI export as an alternative to the current PhoneGap Build export in app edition panel in a future release.
In fact this is already in place internally, just the button is missing.
If you want to test it you can copy the current PhoneGap Build "Export" button link and add **"&export_type=phonegap-cli"** to it and it should launch the PhoneGap CLI export.
( The link should be something like: /wp-admin/post.php?post=123&action=wpak_download_app_sources&_wpnonce=1234e5678&export_type=phonegap-cli)

Don't hesitate for any further info and to give us feedback about this Phonegap CLI export feature.

**Comment by gerhardsletten** [comment]
Thanks!
