### ISSUE TITLE
Deep link

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#215]
Merge feature_deep_link branch into development

**Comment by lpointet** [comment]
using this page: http://benjaminlupu.net/tests/deep-links/

[3:27] 
Tests I've done:
- Click each link + app launch (not background)
- Click each link + app returning from background
- On Android + iOS
- Try to go back

[3:27] 
I use the uncatcrea:// scheme

[3:30] 
Everything went well on Android except for comments (but I suspect it is a problem with the half finished Q theme)

[3:32] 
Regarding ​*iOS*​ Single, List and Page works when app is not returning from background

[3:34] 
​*When returning from background*​, displaying a list when a single or a page is the previous screen -> works

[3:35] 
As soon as a list a the current screen, you access to single or page is no more possible with a deeplink

[3:36] 
Also when the current screen is a post, you can switch to a page but after that, you're blocked

[3:36] 
My guess: you're blocked after the second access?

[3:37] 
Comments never work

**Comment by lpointet** [comment]
As discussed and test, 2 issues persist:
* comment screen breaks history and back button when accessed directly, especially for pages. Will be addressed in #218 
* _resume_ event doesn't trigger the plugin's method to know if a link has been clicked. This happens for example in Android when the app has firstly been launched thanks to a deep link and this exact same link is used again to resume it (when it was in background). This has been reported to plugin's author here: https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/140#issuecomment-216050164

Except for these, everything's working fine in both platforms.

**Comment by MakarkinPRO** [comment]
does branchs works right now?

**Comment by lpointet** [comment]
Hi @MakarkinPRO!
Thanks for your interest.
This feature is currently merged into [development ](https://github.com/uncatcrea/wp-appkit/tree/development) branch, which is still in "development", so it might be dangerous to use it for real projects.
We'll release a new stable version soon, including this "Deep Link" feature, so keep in touch to know when it comes :).

**Comment by MakarkinPRO** [comment]
I know the Branch has their own SDK for PhoneGap. Probably you know about that) Is it possible to transfer your PhoneGap code to Xamarin?

**Comment by lpointet** [comment]
This plugin allows you to export an hybrid app to be compiled thanks to Cordova/PhoneGap.

AFAIK, there is no tool to automatically migrate from this type of development to a Xamarin one.
There are many differences between these 2 technologies, especially the fact that Cordova/PhoneGap requires web technologies (HTML/CSS/JS) while Xamarin app development is using C#.

Since our plugin is bound to WordPress, it seems a good idea to use the same languages to create mobile app: this is why there is no way to have a WP-AppKit app with Xamarin.
