### ISSUE TITLE
User's signup satisfaction

### ISSUE THREAD

**Issue by MakarkinPRO** [uncatcrea/wp-appkit#237]
Is it possible to integrate phone/sms signup/auth/restore password options. And make a phone number as a identificator in WordPress rather than email/password?

**Comment by blupu** [comment]
Hi,

WP-AppKit supports WordPress authentication. So you'll need to modify the way WordPress handles authentication first. Note that WP-AppKit doesn't take care of password recovery, you'll have to redirect users to the WordPress page dedicated to that. At last, note that we support default WordPress authentication methods (login/email). So we don't support and have not tested other ways such as phone number based.

http://uncategorized-creations.com/2323/wordpress-user-authentication-in-wp-appkit/

**Comment by MakarkinPRO** [comment]
oh ok thx.
