### ISSUE TITLE
Problems with the new version

### ISSUE THREAD

**Issue by hakansenturk** [uncatcrea/wp-appkit#238]
Hi, thanks for great job. I am using your plugin and created a mobile app. The problem is when I back from a blog post, in the previous version I exactyly go to the latest position of blog list, but with the latest update the post list goes to the top. Is there any solution for this ?

Another problem is, the back button of the phone can not exit program, you have to press too many times to exit, how can i add a exit button to the menu, or can i change the behavior of the back button ?

Thanks a lot.

**Comment by hakansenturk** [comment]
I tried to play with the code, I don'T understand but I deleted the line  

$wrapper.empty().append( $next ); // reload underlying screen        

from functions.js and everything is normal, after reading the post and back to post list, it goes to the same position and problem solved. Is there anything bad with removing this line from functions.js ?

**Comment by blupu** [comment]
Hi,

Deleting `$wrapper.empty().append( $next ); // reload underlying screen` is a problem as it triggers events such as _screen:showed_. It shouldn't have impact on scroll position.

Could you confirm you're using _Q for Android_?

If so, the code handling scroll positioning is in _transition_previous_screen_ function.

```javascript
                // If we're returning to a list, scroll to the memorized scroll position in the list
                if (next_screen.screen_type == "list") {
                    var pos = Storage.get("scroll-pos",next_screen.fragment);
                    if (pos !== null) {
                        $next.scrollTop(pos);
                    } else {
                        $next.scrollTop(0);
                    }
                }
```

Could you check that `if (next_screen.screen_type == "list") {`is correctly executed?

**Comment by hakansenturk** [comment]
Hi Blupu, thanks for your answer and attention. What I exactly have done is; I did not update the plugin on Wordpress backend, I have just downloaded the new version from github and uncompress the zip file and overwrite my existing project folders. Everything works fine, but I realised that in my previous android application the scroll position is maintained but in this version when I back from the post to the post list the screen goes to the top, to the first post. 

I tried to solve the problem although I don't have enough knowledge. So, I discovered this;


  /* I deleted this line
                $wrapper.empty().append( $next ); // reload underlying screen
  */
                
                $currentPanelContent.empty(); // empty the current slide up panel content
                
                // If we're returning to a list, scroll to the memorized scroll position in the list
              
                if (next_screen.screen_type == "list") {
                    var pos = Storage.get("scroll-pos",next_screen.fragment);
                    
                    if (pos !== null) {
                        $next.scrollTop(pos);
                      
                    } else {
                        $next.scrollTop(0);
                    }
                }

I think           if (next_screen.screen_type == "list") {       is not correctly executed. Should I have to update the plugin on wordpress site, I just replaced files with the new ones and compiled and run with cordova. 

By removing that line now, the app works fine, goes back to the correct position.

But as you say, deleting that line is nothing to do with the position.

I am using Q for Android, I think I made something wrong but I don't know where :-)

**Comment by blupu** [comment]
_Q_ themes (both iOS and Android versions) are compatible with WP-AppKit 0.6+. So, you'll have to upgrade WP-AppKit to version 0.6 first.

- **Backup your current themes first please**
- Deactivate WP-AppKit in WordPress admin
- Replace your current /content/plugins/wp-appkit folder's content by the [new version files](https://github.com/uncatcrea/wp-appkit/releases/tag/v0.6)
- Reactivate WP-AppKit in WordPress admin

**I encourage you to test this upgrade on dev environment first.**

**Comment by hakansenturk** [comment]
Thanks, I will do your suggestions and write the result here.Thanks for your patience for answering my questions.

**Comment by hakansenturk** [comment]
OK. :-) I upgraded as you said and everything works fine. I just want add an exit button, how can I add an exit button to the application because I cannot exit application by pressing back button on android, I have to press several times rapidly to exit, do you have the same problem on android device you use ?

**Comment by blupu** [comment]
Hi, you're right. At the moment our history management doesn't quit app on last back hit. We're going to consider that use case for future release. In the meantime you can implement a button and use `navigator.app.exitApp();`.
