### ISSUE TITLE
PhoneGap plugins duplicates in config.xml

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#24]
I've bumped into the following bug:
- Have declared the status bar plugin manually in the Phonegap config.xml data metabox
- It has resulted having 2 status bar declarations in the config.xml
- PhoneGap Build didn't compile anymore raising an error

We should enhance the duplicate detection to avoid this case.

**Comment by blupu** [comment]
Mathieu, I believe that it has been resolved?

**Comment by blupu** [comment]
@mleroi Did you check that this one has been resolved? (I think so.)

**Comment by mleroi** [comment]
Retested : 
- Add plugin manually in the PhoneGap plugins metabox : 
<gap:plugin name="com.phonegap.plugin.statusbar" />
- export
- the plugin is only there once in config.xml
So the last version of plugin duplication managment seems to solve this.
