### ISSUE TITLE
How can I add admob to application ?

### ISSUE THREAD

**Issue by hakansenturk** [uncatcrea/wp-appkit#241]
I would  like to add admob to my application ? Can I insert ads into post lists ? Do you suggest any plugin that I can use with wpappkit?

**Comment by blupu** [comment]
Hi, most of the time, third party Cordova support is done through dedicated plugins like this [one](https://www.npmjs.com/package/cordova-admob). If it's JavaScript, you will most surely able to integrate it in your app's theme.

**Comment by hakansenturk** [comment]
Thanks a lot.

**Comment by muhamadrid** [comment]
I have tried the plugin mentioned above but ads not showing. Just make sure, where should i put this code?


    var isAppForeground = true;
    
    function initAds() {
      if (admob) {
        var adPublisherIds = {
          ios : {
            banner : "ca-app-pub-XXXXXXXXXXXXXXXX/BBBBBBBBBB",
            interstitial : "ca-app-pub-XXXXXXXXXXXXXXXX/IIIIIIIIII"
          },
          android : {
            banner : "ca-app-pub-XXXXXXXXXXXXXXXX/BBBBBBBBBB",
            interstitial : "ca-app-pub-XXXXXXXXXXXXXXXX/IIIIIIIIII"
          }
        };
    	  
        var admobid = (/(android)/i.test(navigator.userAgent)) ? adPublisherIds.android : adPublisherIds.ios;
            
        admob.setOptions({
          publisherId:      admobid.banner,
          interstitialAdId: admobid.interstitial,
          tappxIdiOS:       "/XXXXXXXXX/Pub-XXXX-iOS-IIII",
          tappxIdAndroid:   "/XXXXXXXXX/Pub-XXXX-Android-AAAA",
          tappxShare:       0.5,
          
        });
 
        registerAdEvents();
        
      } else {
        alert('AdMobAds plugin not ready');
      }
    }
    
    function onAdLoaded(e) {
      if (isAppForeground) {
        if (e.adType === admob.AD_TYPE.INTERSTITIAL) {
          console.log("An interstitial has been loaded and autoshown. If you want to load the interstitial first and show it later, set 'autoShowInterstitial: false' in admob.setOptions() and call 'admob.showInterstitialAd();' here");
        } else if (e.adType === admob.AD_TYPE_BANNER) {
          console.log("New banner received");
        }
      }
    }
    
    function onPause() {
      if (isAppForeground) {
        admob.destroyBannerView();
        isAppForeground = false;
      }
    }
    
    function onResume() {
      if (!isAppForeground) {
        setTimeout(admob.createBannerView, 1);
        setTimeout(admob.requestInterstitialAd, 1);
        isAppForeground = true;
      }
    }
    
    // optional, in case respond to events 
    function registerAdEvents() {
      document.addEventListener(admob.events.onAdLoaded, onAdLoaded);
      document.addEventListener(admob.events.onAdFailedToLoad, function (e) {});
      document.addEventListener(admob.events.onAdOpened, function (e) {});
      document.addEventListener(admob.events.onAdClosed, function (e) {});
      document.addEventListener(admob.events.onAdLeftApplication, function (e) {});
      document.addEventListener(admob.events.onInAppPurchaseRequested, function (e) {});
      
      document.addEventListener("pause", onPause, false);
      document.addEventListener("resume", onResume, false);
    }
        
    function onDeviceReady() {
      document.removeEventListener('deviceready', onDeviceReady, false);
      initAds();
 
      // display a banner at startup 
      admob.createBannerView();
        
      // request an interstitial 
      admob.requestInterstitialAd();
    }
    
    document.addEventListener("deviceready", onDeviceReady, false);

**Comment by blupu** [comment]
Hi, 

For the AdMob part, I cant' answer. This code should go in _functions.js_. However, you don't have to use the _deviceready_ event as JavaScript in _functions.js_ is already loaded when the device is ready.

**Comment by Shidqi92** [comment]
hi, 
can i ask a tutorial for how to add admob to my app?because i don't understand

**Comment by Shidqi92** [comment]
i add this code to functions.js, then please help me to corrections this code and where i input wrong code?

 
	 var app = {
    	//Aplications Constructor
     initialize: function() {
         this.bindEvents();
    },
    	//Bind Event Listeners
   		//
    	//Bind any event that are require on
 		startup, Common event are:
    
 		//'Load','deviceready','offline','online'.
    
    bindEvents: function(){
        document.addEventListener{this.onDeviceReady,false};
    },
   	//device ready Event Handler
    //
    //The scope of 'this' is the event. In order to call the 'receivedEvent'
    //function, we must explicity call'app.receivedEvent (...);'
     
    onDeviceReady: function(){
        app.receivedEvent('deviceready');
 		},

   	//update DOM on a Received Event

    receivedEvent: function(id) {
	
		var parentElement = document.getElementById(id);
  	    var listeningElement = parentElement.querySelector('.listening.');
        var receivedElement = parentElement.querySelector('.received');

        
 	listeningElement.setAttribute('style','display:none;');
    receivedElement.setAttribute('style','display:block:');
        initAd();
        showBannerFunc();
      	showInterstitialFunc();
        
        console.log('ReceivedEvent: ' + id);
    }
};

 //for sake

	var isAppForeground = true;
    
    function initAds() {
      if (admob) {
        var adPublisherIds = {
          ios : {
            banner : "ca-app-pub-XXXXXXXXXXXXXXXX/BBBBBBBBBB",
            interstitial : "ca-app-pub-XXXXXXXXXXXXXXXX/IIIIIIIIII"
          },
          android : {
            banner : "ca-app-pub-2123164715142532/3993648202",
            interstitial : "ca-app-pub-2123164715142532/4992703402"
          }
        };
    	  
        var admobid = (/(android)/i.test(navigator.userAgent)) ? adPublisherIds.android : adPublisherIds.ios;
            
        admob.setOptions({
          publisherId:      admobid.banner,
          interstitialAdId: admobid.interstitial,
          tappxIdiOS:       "/XXXXXXXXX/Pub-XXXX-iOS-IIII",
          tappxIdAndroid:   "/XXXXXXXXX/Pub-XXXX-Android-AAAA",
          tappxShare:       0.5,
          
        });
 
        registerAdEvents();
        
      } else {
        alert('AdMobAds plugin not ready');
      }
    }
    
    function onAdLoaded(e) {
      if (isAppForeground) {
        if (e.adType === admob.AD_TYPE.INTERSTITIAL) {
          console.log("An interstitial has been loaded and autoshown. If you want to load the interstitial first and show it later, set 'autoShowInterstitial: false' in admob.setOptions() and call 'admob.showInterstitialAd();' here");
        } else if (e.adType === admob.AD_TYPE_BANNER) {
          console.log("New banner received");
        }
      }
    }
    
    function onPause() {
      if (isAppForeground) {
        admob.destroyBannerView();
        isAppForeground = false;
      }
    }
    
    function onResume() {
      if (!isAppForeground) {
        setTimeout(admob.createBannerView, 1);
        setTimeout(admob.requestInterstitialAd, 1);
        isAppForeground = true;
      }
    }
    
    // optional, in case respond to events 
    function registerAdEvents() {
      document.addEventListener(admob.events.onAdLoaded, onAdLoaded);
      document.addEventListener(admob.events.onAdFailedToLoad, function (e) {});
      document.addEventListener(admob.events.onAdOpened, function (e) {});
      document.addEventListener(admob.events.onAdClosed, function (e) {});
      document.addEventListener(admob.events.onAdLeftApplication, function (e) {});
      document.addEventListener(admob.events.onInAppPurchaseRequested, function (e) {});
      
      document.addEventListener("pause", onPause, false);
      document.addEventListener("resume", onResume, false);
    }
        
    function onDeviceReady() {
      document.removeEventListener('deviceready', onDeviceReady, false);
      initAds();

      // display a banner at startup 
      admob.createBannerView();
        
      // request an interstitial 
      admob.requestInterstitialAd();

    }
    
    document.addEventListener("deviceready",onDeviceReady, false);

	    //display the banner
	 function showBannerFunc()
	 	{
	    window.plugins.AdMob.createBannerView();
	 	}
	 	
	 	//display the interstitial
	 function showInterstitialFunc()
	 	{    
		window.plugins.AdMob.createInterstitialView();  
	 	
	 	//get the interstitials ready to be shown and show when it's loaded.
	    	
	    window.plugins.AdMob.requestInterstitialAd();
		}
		
app.initialize();

**Comment by lpointet** [comment]
Hi,

As Benjamin said, `functions.js` is called and executed after `deviceready` event has been fired, so you don't need to listen to it: simply call everything that is into your `onDeviceReady` function directly:
```
initAds();

// display a banner at startup 
admob.createBannerView();

// request an interstitial 
admob.requestInterstitialAd();
```

Some other things you need to check:
- be sure to test with a _real_ device, since cordova plugins are not loaded in the browser preview (you probably should require `core/phonegap/utils` into your `functions.js` file and test if PhoneGap lib is available with the following piece of code as well: `if( Phonegap.isLoaded() )`)
- everywhere you can see `XXX`, `BBB` etc. in the code, you should of course replace these strings by real IDs you may have

I hope this helps.

**Comment by lpointet** [comment]
Also, see [our doc about functions.js](http://uncategorized-creations.com/wp-appkit/doc/theme-api/#237-functions-js) to know more about what it is and how you should use/write it.

**Comment by Shidqi92** [comment]
Hi,
Thank's for answer...
but can i ask a example source or how to add that admob step by step? sory for my english less fluent.

**Comment by blupu** [comment]
Hi, I've just published a quick tutorial on how to integrate AdMob in WP-AppKit apps: http://uncategorized-creations.com/2969/how-to-integrate-admod-in-your-wp-appkit-app/.
