### ISSUE TITLE
Integration question

### ISSUE THREAD

**Issue by MakarkinPRO** [uncatcrea/wp-appkit#242]
HI is it possible to integrate Twitter's Digits service into the your wordpres APP in SignUP/AUTH process?
So instead of using email/pass for registration and auth ... use phoneNumber/SmsOtpPasswords?

**Comment by lpointet** [comment]
Hi,

As stated in your last issue (https://github.com/uncatcrea/wp-appkit/issues/237), WP-AppKit only supports standard WordPress authentication, so any other method won't work out of the box.
That being said, you have to modify the way WordPress itself handles authentication, so you might not have to do anything to make it work with WP-AppKit.
Anyway, we didn't test it, so please feel free to share your experience.

Cheers.
