### ISSUE TITLE
Sensivity of the menu list items

### ISSUE THREAD

**Issue by hakansenturk** [uncatcrea/wp-appkit#247]
Is it possible to adjust sensivity of the menu list? When I touch a menu item for going down for example it suddenly opens post list of that category. So you have to select menu item without touching other items when scrolling. It is too sensitive when scrolling and suddenly goes to category list that you dont want to open.

**Comment by blupu** [comment]
Could you tell me which theme (eg. Q for Android) you're using?

**Comment by hakansenturk** [comment]
I am using q for android. Before q for android I was using the previous version and I updated to q for android. Am I doing something wrong?

**Comment by blupu** [comment]
Nothing wrong. I wanted to be sure what source code you're using.

I believe the problem may come from the event I use for menu item events: https://github.com/uncatcrea/q-android/blob/master/js/functions.js#L445

I use touchend. Please try to use click (which comes later in the events cycle).

```JavaScript
$("#app-layout").on( "click", "#menu-items li a", menuItemTapOff );
```

Let me know if it works for you.

**Comment by hakansenturk** [comment]
Hi blupu,thanks for the solution, As you said I changed the line 445 in functions.js with yours as;
$("#app-layout").on( "click", "#menu-items li a", menuItemTapOff );

it worked but it was very hard to select a menu item,  you have to press several times to select a menu item so I tried to change the previous line 444, in line 444 in functions.js I also replaced the touchstart with "click" so problem solved. It works perfectly now. The final code is as follows;

(Functions.js)  

// Menu item events
	$("#app-layout").on( "click", "#menu-items li a", menuItemTapOn );
        $("#app-layout").on( "click", "#menu-items li a", menuItemTapOff );
