### ISSUE TITLE
cb_error is undefined

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#250]
In core/app.js (https://github.com/uncatcrea/wp-appkit/blob/master/wp-appkit/app/core/app.js#L1592), we call "app.triggerError" passing by a "cb_error" argument which doesn't exist, leading to a "Uncaught ReferenceError: cb_error is not defined" error in the console.

**Comment by mleroi** [comment]
I removed this ghost cb_error which caused app crashing with custom components having no or wrong data. 

For the record, I've identified that the error happened when for example a custom component was added to an app without providing the correct hook name or not setting correct data in hook.
