### ISSUE TITLE
Social sharing advice

### ISSUE THREAD

**Issue by hakansenturk** [uncatcrea/wp-appkit#251]
How can I add social sharing buttons to posts, can you advice third party services that I can use with wpappkit?

**Comment by lpointet** [comment]
Hi,
It's possible through a dedicated cordova plugin that will use native sharing methods. We usually include https://www.npmjs.com/package/cordova-plugin-x-socialsharing into our apps, it should do the job.
Enjoy!

**Comment by hakansenturk** [comment]
Thanks a lot. I will try.
