### ISSUE TITLE
PhoneGap Build only outputting x86 binary

### ISSUE THREAD

**Issue by HammyHavoc** [uncatcrea/wp-appkit#252]
Hey guys,

Trying to get my friend's record label/studio app working properly, though I've encountered a strange problem whereas PhoneGap Build only seems to want to output an x86 APK file, here's the repository: https://github.com/HammyHavoc/Aquafight-Records-for-Android

Will get him to credit you in the app launch mention and link to you.

**Comment by lpointet** [comment]
Hi!

You're right, PhoneGap Build is adopting strange behaviours regarding architecture... You can use the following plugin to select for which architecture you want to build: https://github.com/MBuchalik/cordova-build-architecture.git

See [this comment](https://github.com/MBuchalik/cordova-build-architecture.git) for an explanation.
