### ISSUE TITLE
Could we get an option to allow installations to SD cards on Android?

### ISSUE THREAD

**Issue by HammyHavoc** [uncatcrea/wp-appkit#253]
http://ourcodeworld.com/articles/read/171/how-to-enable-the-move-to-sd-card-feature-in-a-cordova-app-for-android

**Comment by lpointet** [comment]
Hi,

This seems to be a feature we should have a look to. My guess is we provide a way to easily select the install location for developers, but not directly through the app edit screen, as this could be a bit tricky/confusing for end users.
I keep this issue open for us to review it during next release planning.

Thanks for your suggestion!

**Comment by lpointet** [comment]
Quick note about implementation: it seems we won't need any plugin to update AndroidManifest.xml anymore, since there is a beta feature about it documented [here](http://docs.phonegap.com/phonegap-build/configuring/config-file-element/).

**Comment by blupu** [comment]
Hi, it seems we can use a preference for that: _android-installLocation_. See http://docs.phonegap.com/phonegap-build/configuring/preferences/. To be tested.

**Comment by blupu** [comment]
Considering closed.

**Comment by HammyHavoc** [comment]
Does `android-installLocation` work okay?
