### ISSUE TITLE
How to limit excerpt length by characters

### ISSUE THREAD

**Issue by muhamadrid** [uncatcrea/wp-appkit#255]
How to limit excerpt length by characters. I tried this but it didnot work.

`	function wpak_excerpt_length( $length ) {
		return 20;
	}
	add_filter( 'excerpt_length', 'wpak_excerpt_length', 999 );`

**Comment by blupu** [comment]
Below an example on how you may limit excerpt length **only for app's display**. That code goes into a _.php_ file located into the _php_ folder of your **app's theme**.

```php
function wpak_limit_excerpt( $post_data, $post, $component ) {
    
    // Limit the excerpt to 20 characters and add ... at the end (mbstring must be activated)
    $post_data['excerpt'] = mb_strimwidth($post_data['excerpt'], 0, 20, "...");;
    
    return $post_data; // Return the modified $post_data

}

// We use the wpak_post_data hook to modify the data returned by the web service
add_filter( 'wpak_post_data', 'wpak_limit_excerpt', 10, 3 );
```
