### ISSUE TITLE
How to  retrieve specific thumbnail size?

### ISSUE THREAD

**Issue by muhamadrid** [uncatcrea/wp-appkit#256]
Hi, I am really noob about this. How to add and retrieve specific thumbnail size? Lets say, I wanna add 90x90px image size and crop it to the center to maintain image proposional dimension and dispay it on archive template.

**Comment by blupu** [comment]
Hi this is more a WordPress question than a WP-AppKit question. Please see articles like:

- https://havecamerawilltravel.com/photographer/wordpress-thumbnail-crop
- https://havecamerawilltravel.com/photographer/wordpress-resize-thumbnails

**Comment by muhamadrid** [comment]
I amsorry let, me correct myself. I have two thumbnail size, lets call it 'medium' and 'large'.  I know how to display those thumbnail size on wordpress theme, but I dont know how to display it on wp-appkit. Wp-apkit only show 'full' size thumbnail on its default theme.

**Comment by lpointet** [comment]
Hi,
In that case, you want to add additional data to the webservice, so you have to use a filter like `wpak_post_data` (see [our doc about it](http://uncategorized-creations.com/wp-appkit/doc/app-content/#1668-wpak_post_data)).
You can use a code like the following:
```
function add_medium_size( $post_data, $post, $component ) {
    $post_featured_img_id = get_post_thumbnail_id( $post->ID );
    $post_data['medium_img'] = ''; // Empty default value to be consistent with WP-AppKit 'thumbnail' data

	if ( !empty( $post_featured_img_id ) ) {
		$featured_img_src = wp_get_attachment_image_src( $post_featured_img_id, 'medium' );
		if( !empty( $featured_img_src ) ) {
                    $post_data['medium_img'] = array(
                        'src' => $featured_img_src[0],
                        'width' => $featured_img_src[1],
                        'height' => $featured_img_src[2],
                    );
		}
	}

    return $post_data;
}

add_filter( 'wpak_post_data', 'add_thumbnail_size', 10, 3 );
```

You'll then be able to access `post.medium_img` from your theme.

**Comment by muhamadrid** [comment]
The image jst missing when I insert this code.

`					<% if( post.medium_img.src && post.medium_img.length ){ %>
						<img class="media-object" style="width: 95px; height: 95px;" src="<%= post.medium_img.src %>">
					<% } %>	`

**Comment by lpointet** [comment]
I guess `post.medium_img.length` is undefined here. Did you try logging what you are receiving? You can also click on "Show Me Web Service Data" button to see what the webservice is really sending to your app.

**Comment by muhamadrid** [comment]
`"medium_img":{"src":"http:\/\/balikbandung.com\/wp-content\/uploads\/2016\/08\/Pemain-Persib-Bandung-Maung-Bandung-Berita-Persib.jpg","width":848,"height":496
`
The thumbnail is not change.

**Comment by lpointet** [comment]
Did you copy/paste my code as is? Do you really have a custom image size called 'medium' with 95x95px?
If not, you have to change 'medium' by the name (or dimensions) of your real size.
Also, you can check what WordPress outputs when using `<?php the_post_thumbnail( 'medium' ); ?>`.

**Comment by muhamadrid** [comment]
Allright this is the actal code.

On my wordpress theme
```
<?php the_post_thumbnail( '263x269' ); ?>
```

On my wp-appkit php file
 
```
function add_263x219_size( $post_data, $post, $component ) {
    $post_featured_img_id = get_post_thumbnail_id( $post->ID );
    $post_data['263x219_img'] = ''; // Empty default value to be consistent with WP-AppKit 'thumbnail' data

    if ( !empty( $post_featured_img_id ) ) {
        $featured_img_src = wp_get_attachment_image_src( $post_featured_img_id, '263x219' );
        if( !empty( $featured_img_src ) ) {
                    $post_data['263x219_img'] = array(
                        'src' => $featured_img_src[0],
                        'width' => $featured_img_src[1],
                        'height' => $featured_img_src[2],
                    );
        }
    }

    return $post_data;
}

add_filter( 'wpak_post_data', 'add_263x219_size', 10, 3 );

```
On my archive.html

```
<% if( post.263x219_img.src && post.263x219_img.src.length ){ %>
	<img class="media-object" style="width: 95px; height: 95px;" src="<%= post.263x219_img.src %>">
<% } %>		
```
The archive is not display content. There is only navigation header which show up.

**Comment by lpointet** [comment]
Do you have any error in the console?
You probably should try naming your variable differently, I guess `263x219_img` isn't really appreciated here. Could you try with something like `test_img` (or anything containing only alphabetical characters)?

**Comment by muhamadrid** [comment]
Yeay, It worked now... I change `263x219_img` with 'test_img" as you said.
Many thanks @lpointet . Your support is cool.

**Comment by lpointet** [comment]
No problem, glad to see your issue is fixed.
