### ISSUE TITLE
missing valid header

### ISSUE THREAD

**Issue by Malome13** [uncatcrea/wp-appkit#258]
Hi, I am trying to create an app for my wordpress site and each time it says plugin missing valid header, can you please help.

**Comment by mleroi** [comment]
Hi, 
In last release (see #233), we fixed a problem that was causing this "missing valid header" issue.

Could you confirm that you're using version **0.6** of WP-AppKit and that you downloaded the zip (or cloned) from the **master** branch ?

**Comment by Malome13** [comment]
I used the version 0.6 zip version from the master branch. Can i give you my credentials so you can sign in and try installing it yourself?

**Comment by mleroi** [comment]
Yes you can send us your credentials using our contact form http://uncategorized-creations.com/contact-us/ and we'll take a look.

**Comment by mleroi** [comment]
As seen directly via email support, this was maybe a header cache problem as the install went just fine when we tried it from an external computer.
