### ISSUE TITLE
"Universal" platform option

### ISSUE THREAD

**Issue by HammyHavoc** [uncatcrea/wp-appkit#26]
Offering a "Universal" platform option when creating/editing an application would be a good goal to aim for after the beta so that Phonegap Build can compile apps for each platform from one zip file, yet still offering the ability to keep apps per platform separate is also a good option as not everybody will want the same UI/UX per platform.

**Comment by mleroi** [comment]
Cool thanks Lionel! :D
Seems perfect to me

**Comment by lpointet** [comment]
2 points we need to test:
* platform specific fields and metaboxes should all be displayed when "Universal" is selected
* how are icons and splashscreens handled by PhoneGap Build?

**Comment by blupu** [comment]
We'll stay with the policy to have one app per platform.
