### ISSUE TITLE
content update question for q for android

### ISSUE THREAD

**Issue by hakansenturk** [uncatcrea/wp-appkit#260]
Hi, after starting android application I created, the application begins to update wordpress post list. During this update process, If I enter a post from the list, it normally displays the post but after updating process is finishes, the program goes back to post list automatically.

In the previous version, I remember, I can read the post during the update and after the content update finishes.

I do not want the program goes back to post list after content update finishes. Is it any solution for this ?

**Comment by blupu** [comment]
Yes I believe so.

Displaying the default screen after refresh is done in the _refresh:end_ event with the _App.navigateToDefaultRoute();_ in _[functions.js](https://github.com/uncatcrea/q-android/blob/master/js/functions.js#L263)_.

You can test if the current screen is a single and stop the routing to the default (refresh will still be done).

Here is a quick example on how to do it:

```javascript
    var currentScreenObject = App.getCurrentScreenObject();

    // Navigate to the default screen (if we are not displaying a single)
    if ( currentScreenObject.screen_type !== 'single' ) {
        App.navigateToDefaultRoute();
    }

```

Of course, you can test for additional screen types if necessary.

**Comment by hakansenturk** [comment]
**That sounds great! Thanks a lot for quick response :-) :+1:**

**Comment by hakansenturk** [comment]
Hi, as you suggested I replaced the line **App.navigateToDefaultRoute();** in functions.js with the following;

// Navigate to the default screen
        
        
         var currentScreenObject = App.getCurrentScreenObject();

    // Navigate to the default screen (if we are not displaying a single) 
    if ( currentScreenObject.screen_type !== 'single' ) {
        App.navigateToDefaultRoute();
    }


it works :-), but the problem is after refresh is completed, I cannot go back to previous screen by pressing the back arrow button on the screen. But I can only go back by pressing the phone's back button. I could not find the solution for this.
