### ISSUE TITLE
itunesconnect shows default phonegap icon after upload.

### ISSUE THREAD

**Issue by xanxion** [uncatcrea/wp-appkit#267]
When uploading build to iTunesConnect, it shows default Phonegap icon, something like this:
76@2x.png

Maybe phonegap icons are supposed to be in a specific folder like this?:
/res/icon/ios/
- or there is some missing iOS icons after exporting from Wp AppKit?

![doit](https://cloud.githubusercontent.com/assets/11750696/18605151/5bd2d472-7c8a-11e6-9559-4f70714ad3e4.png)

**Comment by blupu** [comment]
Hi, you're right, there's missing iOS resources if [this article](https://makeappicon.com/ios10icon) is right. We're going to fix that in the next version. In the meantime, you can add these missing resources in the export .zip (in the _icons_ subfolder).

**Comment by xanxion** [comment]
It dosnt seem to work by adding icons in the icons folder, since phonegap places icons in the root folder of the IPA file (exported from Phonegap)
![don1](https://cloud.githubusercontent.com/assets/11750696/18607837/f523c8ae-7cd8-11e6-985e-953fd9c822e1.jpg)

**Comment by xanxion** [comment]
Fixed the issue by referencing to the icons in config.xml
