### ISSUE TITLE
Introduce support for Tizen in Phonegap Build

### ISSUE THREAD

**Issue by HammyHavoc** [uncatcrea/wp-appkit#269]
Relatively niche OS, but PhoneGap Build seems to support it, same with Windows Mobile.

**Comment by blupu** [comment]
I @HammyHavoc, I hope you're doing well. I believe Cordova (and therefore [PhoneGap](http://docs.phonegap.com/en/2.2.0/guide_getting-started_tizen_index.md.html)), supports Tizen. However, we won't add support for Tizen in WP-AppKit for the moment (even I love the open source principle behind it). We use our resources and time for OS mainly adopted by our users (iOS and Android).
