### ISSUE TITLE
wpak_unavailable_media.png appears unexpectedly in a single post

### ISSUE THREAD

**Issue by HammyHavoc** [uncatcrea/wp-appkit#27]
In the only post on https://www.hammyhavoc.com, https://www.hammyhavoc.com/wp-content/uploads/wpak_unavailable_media.png appears as an image randomly in the post where a hyperlink should be rather than any kind of image, this doesn't seem to be down to any particular WP-AppKit theme, I've tried it using the following:

* Nihao-android
* Nihao-ios
* Bootstrap
* Wp-marmite-ios

The paragraph snippet is as follows:
```
Myself, <a title="Dan Booth Presents The Boo Tube" href="http://www.thebootube.com">Dan</a>, <a title="The Alice Jones Official Website" href="http://www.thealicejones.com">Alice</a> and <a title="Bryan Desrosiers Official Website" href="http://www.bryandesrosiers.com">Bryan</a> are hard at work to bring Previous Magazine in new ways to our cult following, we're especially eager to get into video content as a publication as well as individually yet in a collaborative way within our scene and working with some old friends of mine including <a title="Puma Yage TV's YouTube Channel" href="https://www.youtube.com/channel/UCHRS7NDZcLvvGkEGKF-fDpg">Puma Yage</a>.
<h2>My gear so far in 2014</h2>
```

I've temporarily made the app public, you can view it here if you want to take a look at the source: https://www.hammyhavoc.com/wp-content/plugins/wp-app-kit/app/index.html?wpak_app_id=hammy-havoc-ios#single/posts/929

**Comment by blupu** [comment]
@mleroi The link to the source code raises a 404. Could you fix it?

**Comment by blupu** [comment]
@mleroi I thought that we had these limitations deleted - Is that the case?

**Comment by mleroi** [comment]
I never really did this indeed... It's ok now, I've removed all our post content pre formating concerning videos / audio embeds/iframes.

As we discussed, it's now in the user's hands to choose what he removes/formats regarding embeds/iframes in his content, using our post content hooks : "wpak_post_content" and "wpak_post_content_format".
