### ISSUE TITLE
[User Question] WooCommerce/Shop Functionality

### ISSUE THREAD

**Issue by Caffeineli** [uncatcrea/wp-appkit#270]
Although we can display WooCommerce products as a post type, do you have plans to release any documentation around the implementation of a full shop?

I've been looking around and can't find any tutorials to help implement this functionality. Do any of your current tutorials hold the secret to this type of customization?

In the FAQ, you've said "However, you’ll have to (re)develop functionalities such as cart or checkout." I was wondering if you have attempted it yourselves.

Thanks so much, Eli.

**Comment by blupu** [comment]
Hi, I am afraid we didn't develop such integration. We'll surely try in the future. At the moment, we're working on proposing ready to use integrations for Google Analytics and PushWoosh. Sorry that we can't answer to your need right now.

**Comment by Caffeinaation** [comment]
Hi @blupu, thanks for letting me know!
