### ISSUE TITLE
Can not add url to image in wp-appkit page, possible solution?

### ISSUE THREAD

**Issue by xanxion** [uncatcrea/wp-appkit#272]
Hi developers!

We really need to add some images in a wp-appkit page that links to specific posts.
But when we try it gets stripped (probably because post image urls need to go to their post.

Isnt it possible to do something like:
in:  prepare-content.php

IF POST PAGE/Post categories -> (where its needed) DO:
    $imgCollection1 = $xpath->query("//a/img");
    
    foreach($imgCollection1 as $img) {
        $img->parentNode->removeAttribute('href');
        $img->parentNode->setAttribute('class','content-image-link');
    }

ELSE (on a specific wp-appkit page where its not needed so we can add urls to images) DO:
Nothing..

I am not a php coder, but im guessing that code above which is stripping the urls on images is not needed in a specific wp-appkit page.
Where we actually need to add some images with urls.

Love this system apart from this!

**Comment by blupu** [comment]
Hi @xanxion thinking about your question, you probably should suppress this hyperlinked images processing in _prepare-content.php_. Then you could do this processing in the app's theme. For example, you can detect in _screen:showed_ event which post or page has been displayed to process it correctly (or better do it in the transition before for better performance).
