### ISSUE TITLE
Add x86/ARM compilation choice in PhoneGap Build export settings

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#275]
Following discussion here https://github.com/uncatcrea/wp-appkit/issues/252 and on support threads (hello Philippe!), we should consider allowing the user to choose between x86 or ARM compilation directly from app edition, in PhoneGap Build settings.
In a nutshell this would mean adding the following to config.xml when the user wants to force ARM compilation:
- include the plugin "cordova-build-architecture"
- add the following line to config.xml: `<preference name="xwalkMultipleApk" value="true" />`

**Comment by theophilbethel** [comment]
Great !
Thanks Mathieu, this useful improvement will solve this PGB strange behaviour.
Till then, this workaround will help : [(https://forums.adobe.com/message/8841023#8841023)].
And, by the way, happy new year !
Philippe

**Comment by HammyHavoc** [comment]
@theophilbethel, that Adobe URL doesn't work as expected.

**Comment by lpointet** [comment]
@HammyHavoc I just updated the link in the comment above so that it works as expected ;).
