### ISSUE TITLE
Custom Query Post

### ISSUE THREAD

**Issue by muhamadrid** [uncatcrea/wp-appkit#276]
Hello, how to query post on the specific page template? For example, I have this code on my wordpress theme.

$the_query = new WP_Query( array( 'category_name' => 'nu-aink', 'posts_per_page' => 3 ) )
php if ( $the_query->have_posts() )
while ( $the_query->have_posts() ) : $the_query->the_post()
<div id="post-<?php the_ID(); ?>" class="posts__inner post_dark">
  the_title ()
</div>
endwhile;
wp_reset_postdata()
else
<p> _e( 'Sorry, no posts matched your criteria.' ) </p>
endif

Thanks.

**Comment by mleroi** [comment]
Hi,
To display a list of posts from a given category ("nu-aink" here), you can just add a "Post list" component with taxonomy "Category" and Category "nu-aink" in your app edition panel in WP back office. Then add this component to your app Menu (In the "Appearance" box).
Then your category will display in the app using the _archive.html_ template of your WP-AppKit theme.
If you want to use a specific template for this specific category, it's explained here: http://uncategorized-creations.com/2381/customize-wp-appkit-templates/.
Hope this helps

**Comment by muhamadrid** [comment]
Ok i understand that parts. But how to display custom querys on custom page template. Lets say I have custom page template called home.html. On that page, i wanna retrieve list of post from more than categories which i have. On wordpress theme, i just add and duplicate codes above.

**Comment by mleroi** [comment]
For that you'll use the "wpak_posts_list_query_args" filter on WP side, which allows to do any customization that you can do with WP_Query. An example here: https://gist.github.com/uncatcrea/c4489844129ad86ffa9f

**Comment by muhamadrid** [comment]
Done. Now i have function like this on my add-custom-data.php

function my_custom_query( $query_args, $component ) {
	
	if( $component->slug === 'home' ) {
		$query_args['orderby'] = 'name';
		$query_args['order'] = 'ASC';
		$query_args['category_name'] = 'nu-anik';
		$query_args['post_per_page'] = '5';		
		//see https://codex.wordpress.org/Class_Reference/WP_Query#Order_.26_Orderby_Parameters
	}
	
	return $query_args;
}
add_filter( 'wpak_posts_list_query_args', 'my_custom_query', 10, 2 ); 

Next question, how to display this query on custom page template. What code should i copied?

**Comment by mleroi** [comment]
To chose a custom template for your component on app side, you'll use (in your WP-AppKit theme's functions.js):
```
App.filter( 'template', function( template, current_screen ) {
	if ( current_screen.component_id === 'my-component-slug' ) {
		template = 'my-template';
	}
	return template;
} );
```
Other examples here: http://uncategorized-creations.com/3180/custom-templates/

**Comment by muhamadrid** [comment]
Ok, now i have add this code to my function.js

 App.filter( 'template', function( template, current_screen ) {
	if ( current_screen.component_id === 'home' ) {
		template = 'home';
	}
	return template;
} );

But now i got error 

Uncaught ReferenceError: posts is not defined
    at s.eval (eval at j.template (underscore.js?wpak_app_id=ccc&bust=1484820494156:1), <anonymous>:6:5)
    at s.c [as template] (underscore.js?wpak_app_id=ccc&bust=1484820494156:1)
    at s.render (page.js?wpak_app_id=ccc&bust=1484820494156:1)
    at openView (region-manager.js?wpak_app_id=ccc&bust=1484820494156:1)
    at showView (region-manager.js?wpak_app_id=ccc&bust=1484820494156:1)
    at switchScreen (region-manager.js?wpak_app_id=ccc&bust=1484820494156:1)
    at region-manager.js?wpak_app_id=ccc&bust=1484820494156:1
    at backbone-template-view.js?wpak_app_id=ccc&bust=1484820494156:1
    at Object.execCb (require.js:1)
    at X.check (require.js:1)

**Comment by mleroi** [comment]
Did you create a component of type "Posts list" and "List type = posts" (not "Custom, using hook") ?

**Comment by muhamadrid** [comment]
Yes. I have 3 component of type "Post list" and 1 component of type "wordpress page".

Please take a look at this image.

![tes](https://cloud.githubusercontent.com/assets/20907600/22103663/a0bd6ae8-de6e-11e6-9d94-e4ecc4e12e16.jpg)

**Comment by mleroi** [comment]
Ok, I'm not sure what you want to achieve exactly as I see it seems you need to display different post lists in a same template, which is quite specific. 
Can you please write to our support : support[at]uncategorized-creations.com so that we can find the best solution for this specific need? (And if you can attach your functions.js and home.html template to this email, it could help)

**Comment by muhamadrid** [comment]
Yep you right, i need to display different post list in a same template. Ok, i will send the file to your supports. Thanks..

**Comment by muhamadrid** [comment]
Hello @mleroi i have sent email to you. Please take a look. Thanks
