### ISSUE TITLE
display component in theme

### ISSUE THREAD

**Issue by roholdt** [uncatcrea/wp-appkit#279]
Putting this in the template works:
TemplateTags.getComponent('my-list');

In my case, the component is a posts list, composed of posts of a category. What i cannot understand, is how to loop through the posts to display them. I will be displaying posts from two categories, separately in the same template. So, I need to loop through two lists of posts – two components created in wp-admin.

Assuming the component type 'posts-list' is recognised as such by the theme, I tried looping through 'my-list' the way 'posts' is looped in the default ios theme, but it doesn't work. 

I can console log it, and see the ids, the taxonomy, and, if I dig deep enough, an 'attributes' variable, which appears to contain the entire post. I guess I can simply get the information that way, but it seems there should be a simpler way. If the template knows about my component, and what it contains, why isn't it able to loop through it the way it does 'posts'?

**Comment by roholdt** [comment]
Or just something like wordpress's get_post(post-id)

**Comment by mleroi** [comment]
Hi!
We're going to publish an article in the coming days that adresses this problematic of displaying more than one post loop in a template.

Until then, here is an example that displays in one template the last 3 posts of 2 components "blog" and "tutorials":

To retrieve posts from a component to be used in template, you'll use: `TemplateTags.getComponent('blog').view_data.posts.toJSON()` (we may implement a function that would directly return the JSONified version of a component's posts in the future).

To pass data to templates, the best is to use the "template-args" filter like so:
```
App.filter( 'template-args', function( template_args, view_type, view_template ) {
	if ( view_template === 'your-template') { //Don't need .html here

		//Get blog posts from our "blog" component and keep only 3 of them to display in template:
		template_args.blog_posts = _.last( TemplateTags.getComponent('blog').view_data.posts.toJSON(), 3 );

		//Same with tutorials posts, from our "tutorials" component:
		template_args.tutorials_posts = _.last( TemplateTags.getComponent('tutorials').view_data.posts.toJSON(), 3 );

		//Now "blog_posts" and "tutorials_posts" variables are available in the "your-template" template :)
	}
	return template_args;
} );
```
Then in your template you can use "blog_posts" and "tutorial_posts" like so:
```
<h2>Blog</h2>
<% if( blog_posts.length ){ %>
	<% _.each( blog_posts, function( post ){ %>
		<div class="content-item has-ripple-feedback">
			<a href="<%= TemplateTags.getPostLink( post.id, 'posts' ) %>">
				//DISPLAY YOUR POST DATA HERE, as you would do in archive.html
				//Also not the use of 2 argument 'posts' in previous getPostLink() call:
				//it's required here because we're in a custom screen, no in a
				//default archive screen.
			</a>
		</div>
	<% }); %>     
<% }else{ %>
	<div class='content-message'>No Blog post found</div>
<% } %>
        
<h2>Tutorials</h2>
<% if( tutorials_posts.length ){ %>
	<% _.each( tutorials_posts, function( post ){ %>
		<div class="content-item has-ripple-feedback">
			<a href="<%= TemplateTags.getPostLink( post.id,'posts' ) %>">
				//DISPLAY YOUR POST DATA HERE, as you would do in archive.html
			</a>
		</div>
	<% }); %>
<% }else{ %>
	<div class='content-message'>No Tutorials post found</div>
<% } %>
```
I hope this helps, don't hesitate for further questions.

**Comment by roholdt** [comment]
Wow, that was quick. I was just about to say I found a somewhat clunky way to get what I needed from the returned object: 

var post-list = TemplateTags.getComponent('slug').view_data.posts.models
and then loop through them like:
_.each(post-list, function(list-item){
var item = list-item.attributes;
}

But I think I'll do it your way instead. Thanks!

**Comment by mleroi** [comment]
Great if that works for you :)
What you found (using view's Backbone models) would work, but using the toJSON() version of posts will be more consistent with how templates data is handled by core (https://github.com/uncatcrea/wp-appkit/blob/master/wp-appkit/app/core/views/archive.js#L29), the philosophy being not to have to deal directly with Backbone in WP-AppKit themes, but with JSON data only.
