### ISSUE TITLE
cannot compile any app

### ISSUE THREAD

**Issue by ecollart** [uncatcrea/wp-appkit#281]
Hello,
not sure it's the right place to contact your support but I am unable to compile any app for Android using PhoneGap, being Grandle or Ant compiler... Both return errors
I use WP-AppKit 0.6.1 on WordPress 4.7.2...
This WordPress plugin looks just fantastic ! I just hope I did something wrong.

Thanks for any help

Eric Collart
Belgium

**Comment by blupu** [comment]
Hi Eric, this repository dedicated to the plugin itself. Could you send us an email to support[at]uncategorized-creations.com? (BTW could you tell us if you try to compile with PhoneGap Build or Cordova/PhoneGap CLI?)

**Comment by blupu** [comment]
It appears that WP-AppKit compilations for Android fail since PhoneGapBuild CLI default version has been updated to 6.50. 

To solve the issue: edit config.xml and chnage spec="1.5.0" to 2.3.0 - we're going to release WP-AppKit 0.6.2 as quick as possible.

**Comment by mleroi** [comment]
Fixed in last release v0.6.2: https://github.com/uncatcrea/wp-appkit/releases/tag/v0.6.2
