### ISSUE TITLE
Set scroll position of next screen

### ISSUE THREAD

**Issue by roholdt** [uncatcrea/wp-appkit#283]
I am building off of the default ios theme, so hopefully the functions I'm referring to will be familiar. 
I want to set the scroll position on a specific page before it is shown, by triggering a function via the existing functions transition_slide_next_screen/transition_slide_previous_screen/transition_default, passing $next to my function. 
The previous-function already does this, I only added some code of my own to the if-statement, and to the next and default functions. What I added is basically this:
if (next_screen.component_id == 'special_page') {
  setTheScrollPosition($next);
}
It almost works, so I must be doing something right. The thing is, I know my function fires every time the screen changes, but it does not set the scroll position unless the screen has already been visited. 
Any idea why that might be?

**Comment by blupu** [comment]
Hi @roholdt could you post what `setTheScrollPosition()` does exactly? For example, where does it get/set the scroll position to use? As you may have seen in `transition_slide_previous_screen`, I am getting the scroll position from local storage and I am saving the position in the `transition_slide_next_screen`. In both case I am doing it if the screen is a list.

**Comment by roholdt** [comment]
As far as I can tell, it does the same thing as the if-statement in transition_slide_previous_screen, only I changed the when and to what (and added the same code to transition_slide_next_screen). In case I was missing something obvious by triggering a separate function, I tried setting scrollTop in the transition-function itself, like the Q theme already does – i.e.:
if (next_screen.component_id == 'special_page') {
  $($next).scrollTop(110);
};

And this works too, but, like my original approach, not the first time the page in question is visited after app refresh. I guess what I need to know is, what is different the first time a screen is visited?

**Comment by blupu** [comment]
I am really not sure to get it properly.

You want to scroll to a fixed position everytime you access a custom page?

This scroll position: **is it a fixed number** or **is it the scroll position you were the last time you visited the custom page**?

**Comment by roholdt** [comment]
Yes, I want to scroll to a fixed position every time, no matter where the scroll position was the last time.

**Comment by roholdt** [comment]
But only on this particular page, I hasten to add.

**Comment by roholdt** [comment]
I think ten days is long enough. Closing this question unanswered.
