### ISSUE TITLE
Detect icons available in the theme

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#301]
Following a specific naming convention, we should allow to include PWA icons directly in the theme so that they are automatically shown in app edit screen + embedded in the export if wanted.

A proposed convention would be the following:
 - files must be included into `icons` directory
 - each file must be named `[name]-xx-yy.png` where xx is the width and yy is the height

**Comment by lpointet** [comment]
What I have in mind in terms of UI here.

**1. In case we detect icons in the theme**
* Display a block showing a text like "We detected the following icons in your theme:"
* Show each icon in a row
* Show radio buttons with label "Use these icons?", values "Yes" / "No", default "Yes"
* In case the user selects "No", show textarea + checkbox as currently shown
* In case the user selects "Yes", hide textarea + checkbox

**2. In case we don't detect any icons in the theme**
* Display a block showing a text like "We didn't detect any icons in your theme, you can provide them into the [theme icons path] directory, use the following field to include them via JSON, or use WP-AppKit default ones." (maybe we could add a link to a more detailed post?)
* Show disabled radio buttons, selected value = "No"
* Show textarea + checkbox as currently shown

Plus, changing the "Theme" value would fetch the detected icons in AJAX, and change accordingly the "icons" part of the PWA manifest configuration. 
_Side Note: this means we'd also be able to do a **refresh** feature for the currently selected theme, but I don't see this as really required/useful._

**Comment by lpointet** [comment]
After discussion, we decided the following:
* completely remove the current textarea
* remove checkbox
* if icons are detected, use them
* if no icons are detected, use WP-AppKit default ones
* OK for AJAX on theme change
* refresh feature not required indeed

**Comment by blupu** [comment]
Hi, while working on the PWA branch of _Q for Android_, I was wondering if it would be useful to have _pwa_ subfolder in the _icons_ folder as it may be shared with the mobile app theme (?).

**Comment by lpointet** [comment]
We may add a filter to let developers change the icons directory? Full path, or just the name of it inside the theme?
