### ISSUE TITLE
Any chance of integrating Android Instant Apps?

### ISSUE THREAD

**Issue by HammyHavoc** [uncatcrea/wp-appkit#310]
Hey,

Google's new Android Instant Apps looks like a really useful thing for wp-appkit, and provides more reason for having an app as time goes by. Any chance of integrating Instant Apps?

All the best,
Hammy

**Comment by blupu** [comment]
Hi @HammyHavoc :-) It is not planned at the moment. I am not aware of a Cordova based way to support them. We are focusing our efforts to best PWA possible support.
