### ISSUE TITLE
Wp-appkit + qtranslate-x plugin

### ISSUE THREAD

**Issue by eskaigualker** [uncatcrea/wp-appkit#312]
Does anybody know how to use this plugin to translate the posts?

Thanks

**Comment by blupu** [comment]
Hi, not on our side. We use Polylang. Sorry.

**Comment by eskaigualker** [comment]
Ok, thank you!
Just for if there is one interested, I think the way to do is setting the qtranslate cookie from the app side. Not know if it can be done.
