### ISSUE TITLE
"PhoneGap 1 not supported" on PhoneGap Build?

### ISSUE THREAD

**Issue by HammyHavoc** [uncatcrea/wp-appkit#319]
Hey guys,

Interesting error in the title appears when I attempt to pull https://github.com/HammyHavoc/Collective-of-Misfits-for-Android.git into Build. Any ideas why that might be?

All the best,
Hammy

**Comment by HammyHavoc** [comment]
I hadn't had my coffee!

**Comment by lpointet** [comment]
Hi Hammy,

I guess you updated the PhoneGap version from your WP-AppKit app edit screen (let it blank for the default version), and everything was OK after that, wasn't it?
