### ISSUE TITLE
Error: Remote connection to website failed

### ISSUE THREAD

**Issue by victorbrites** [uncatcrea/wp-appkit#321]
Hi, I'm creating an application and I'm encountering errors after adding a new component. I do not know how to solve the problem that is being indicated, I deleted the theme, plugin and restarted the server, it did not solve.

Error:
[http://database.victorbrites.com/wp-appkit-api/quero-estagio/MDA2YzM5YjAyMGUxOGQ3ZjQ2YmUwMjg1Mjk5MmRjOGNjNDM1NTBjMWYzNjg2YWJhODhhYzllMjllNzhkYWZhYg==/synchronization](http://database.victorbrites.com/wp-appkit-api/quero-estagio/MDA2YzM5YjAyMGUxOGQ3ZjQ2YmUwMjg1Mjk5MmRjOGNjNDM1NTBjMWYzNjg2YWJhODhhYzllMjllNzhkYWZhYg==/synchronization)

Image error:
https://ibb.co/feEJa5

**Comment by mleroi** [comment]
Hi @victorbrites,
It seems the error is due to the fact that some of your posts have empty content which rises a warning in q-android theme.
It is definitely an issue on our side as empty content should not raise a warning.

**Comment by mleroi** [comment]
We will fix that soon, but in the meantime could you try the following:
in q-android/php/prepare-content.php could you add the following snippet at first line of the _wpak_prepare_content()_ function [here](https://github.com/uncatcrea/q-android/blob/master/php/prepare-content.php#L8) :
```
if ( empty( $content ) ) {
	return '';
}
```
and tell us if it's better?

**Comment by victorbrites** [comment]
Thanks! @mleroi 
I added the code to the function, there are no more mistakes.

**Comment by mleroi** [comment]
Great that it works for you :)
I fixed the issue on q-android theme repository, it was actually a [known issue](https://github.com/uncatcrea/q-android/issues/11). The fix will be embedded in next WP-AppKit version.
Thanks for helping us fixing this and have fun building apps with WP-AppKit!

**Comment by Donald3d** [comment]
I am encountering this same problem too.And its getting frustrating .How can you help please 
I installed it for a client .It worked fine for almost a year and suddenly started giving this error

**Comment by lpointet** [comment]
Hi,
Did you try the fix indicated above for the theme you are using? Maybe you installed an old version and you encouter the exact same issue.
If it's not the case, could you please send us an email at our support address (support[at]uncategorized-creations.com), so that we can help you directly.
Thanks.

**Comment by Donald3d** [comment]
As I said it was working before, and just stopped working all of a sudden.
The theme I am using was built on your bootstrap login theme .So I basically just customized the colors interface etc...nothing fancy.
And that theme doesnt have php in it , so where do I edit ?
Thanks for the response

**Comment by Donald3d** [comment]
Please this is really getting frustrating , I have tried everything .I still keep getting "Remote connection.....failed" 
However when I addd only pages to my components and menu I dont get that error, but once I add post list of any kind or combination or category, I get that error.And I can't do without having a post list.Thanks in advance guys 
@mleroi @lpointet @blupu

**Comment by Donald3d** [comment]
Hi guys , I finally got it resolved .A plugin was causing issue .This is the link to the plugin just in case someone encounters something similar 
https://wordpress.org/plugins/wp-external-links/
