### ISSUE TITLE
Problems with compatibility

### ISSUE THREAD

**Issue by victorbrites** [uncatcrea/wp-appkit#322]
I published an application on Google Play created from WP appkit, got a large number of device restrictions, until my device that I used for testing is in the list.

I did not add features to the theme, I used the theme Q Android and after the result I created a theme with only html, the result was the same.

What could be causing this incompatibility?

![download 1](https://user-images.githubusercontent.com/4011465/27802203-b0671190-5ff8-11e7-8ef8-b86173c307db.png)

**Comment by victorbrites** [comment]
Of 13,533 in total, only 363 are compatible after upload

**Comment by mleroi** [comment]
Hi @victorbrites,

This is a common problem and a dirty little secret of PhoneGap Build and Android. It appears that you have to produce 2 separate APK for your app. One is for x86 and another for the ARM devices. PhoneGap Build generates only one at a time and doesn't provide an easy mechanism to handle multiple APK.

So, you'll have to export one for x86 then modify your configuration and export another project for ARM. This solution involves to use a specific Cordova plugin.

1) Include the cordova-build-architecture plugin in your project by adding <plugin name="cordova-build-architecture" spec="https://github.com/MBuchalik/cordova-build-architecture.git#v1.0.1" source="git" /> in the Plugins field (PhoneGap Build > PhoneGap).

2) By default PhoneGap Build outputs x86 signed apps. So first export your app sources as they are and compiled them. It will be your x86 APK.

3) Then add <preference name="xwalkMultipleApk" value="true" /> to the Plugins field. Export again your app's sources and compile it. It will be your ARM APK.

Sign and compile both project then upload them in the Google Play Console. As soon as it is done, your compatibility will be a lot broader.

**Comment by victorbrites** [comment]
Very good, apk file now supports 11,120 devices
Thanks! @mleroi
