### ISSUE TITLE
Be able to retrieve chosen post(s) from server and store them in the app

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#330]
For now we can't display a post that is not in app's Local Storage.
We should be able to dynamically retrieve posts from server and display them in the app.

Here's the function that will alllow it:
```
function getItemsFromRemote( items, options ) {

	options = options || {};

	//Quirk: for now, to retrieve posts from server with liveQuery, 
	//we must provide a component too. So here we retrieve the first
	//"posts-list" component of the app (it's not important that the retrieved
	//posts belong to this component or not).
	var first_list_component = _.findWhere( App.getComponents(), { type: 'posts-list' } );

	if ( first_list_component ) {

		//Call liveQuery to retrieve the given items from server and store them in local storage:
		App.liveQuery(
			{
				wpak_component_slug: first_list_component.id,
				wpak_query_action: 'get-items',
				wpak_items_ids: items
			},
			{
				type: 'update',
				persistent: true,
				success: function( answer, results ){

					var items_found = _.find( results, function( result ) {
						return result.data.new_items.length > 0;
					} );

					if ( items_found ) {
						if ( options.success ) {
							options.success( answer, results );
						}
					} else {
						//Requested posts where not found. Trigger error
						if ( options.error ) {
							//In final function we will trigger an App error event here.
							options.error( { id: 'get-items:items-not-found', type: 'mixed', where: 'app::getItemsFromRemote', message: 'Requested items not found' } );
						}
					}

				},
				error: function( error ){
					//An error event has been triggered, theme will
					//display the error automatically.
					if ( options.error ) {
						options.error( error );
					}
				}
			}
		);

	} else {
		//No post list component found
		//Do nothing. This is temporary: the final feature won't require for 
		//a post list component to exist to retrieve posts from server.
	}
}
```
We should add it to CoreApp directly, with a ThemeApp alias so that it can be called from theme.

Note that the best will be to also update LiveQuery webservice so that we can retrieve posts independently from components, ie without having to provide a component to LiveQuery call.

**Comment by mleroi** [comment]
And here's how to use this function in Q theme's functions.js::openInBrowser() to handle the case where you click on a link to a single post that is not in the app yet:
Replace the _else_ condition [here](https://github.com/uncatcrea/q-android/blob/master/js/functions.js#L749) by:
```
} else { // href begins with # (ie. it's an internal link)

	//Check if dealing with a route to a single post:
	var matches = href.match( /#single\/.+?\/(\d+)\/?/ );
	if ( matches ) {
		//We are trying to display a single post. Get its id and check
		//if it exists in local storage.
		var post_id = matches[1];
		var local_post = App.getItem( post_id );
		if ( !local_post ) {
			//The post is not in local storage: we retrieve it from remote server:
			getItemsFromRemote( [post_id], {
				success: function() {
					//Post retrieved successfully. We can navigate to it:
					App.navigate( href );
				},
				error: function() {
					//Requested post could not be retrieved: can be a network error
					//or that the post does not exist on server.
					//An error event has been triggered: theme will display the error automatically.
				}
			} );
		} else {
			App.navigate( href );
		}
	} else {
		App.navigate( href );
	}

}
```
Note that the definitive way of handling that will be to be able to hook directly to the router's single route to retrieve the asked post automatically from server if it does not exist, without having to hack into theme's openInBrowser(). This will be discussed in an other issue.

**Comment by blupu** [comment]
Quick note: does that work with deeplinks?

**Comment by mleroi** [comment]
Not the above openInBrowser() hack, which is temporary, but the final way (that I'm currently working on) that hooks directly in router will.

**Comment by mleroi** [comment]
This is now implemented on development branch. 
Single and pages can be accessed even if not in the app yet.
Tested with notifications (deeplinks) and in post links inside post contents.

2 events have been introduced so that the theme can handle the moment when a post or page is retrieved from server: _info:load-item-from-remote:start_ and _info:load-item-from-remote:stop_.

A usage example of those events can be found here: [functions.js](https://github.com/mleroi/q-android/blob/load-single-from-remote/js/functions.js#L269), [layout.hml](https://github.com/mleroi/q-android/blob/load-single-from-remote/layout.html#L15), [layout.html](https://github.com/mleroi/q-android/blob/load-single-from-remote/layout.html#L29)(2)
