### ISSUE TITLE
apaereance erro "Warning: Illegal string offset 'current_theme'" help-me

### ISSUE THREAD

**Issue by Eonassis** [uncatcrea/wp-appkit#334]
help-me my app d'not run, white page......

in my app kit, in apearence area this is erro mensage

help-me!!!!

Warning: Illegal string offset 'current_theme' in /home/uninews/www/wp-content/plugins/wp-appkit/lib/themes/themes-storage.php on line 95

Warning: Cannot assign an empty string to a string offset in /home/uninews/www/wp-content/plugins/wp-appkit/lib/themes/themes-storage.php on line 95

Warning: Illegal string offset 'current_theme' in /home/uninews/www/wp-content/plugins/wp-appkit/lib/themes/themes-storage.php on line 13

**Comment by Eonassis** [comment]
label: bug -low
label:1.2
label:core
@mleroi 
@blupu 
@lpointet

**Comment by mleroi** [comment]
Hi,
This is a known bug that's handled in this issue: https://github.com/uncatcrea/wp-appkit/issues/331
We will fix it in next version.
It seems that this bug only happens if there is some other problem with WP-AppKit theme install.
Do you confirm that you see app themes (Q for Android and Q for iOS) in the select box in your app edit panel > "Appearance" > "Chose Theme" and that you have one selected for your app?

**Comment by Eonassis** [comment]
P:and that you have one selected for your app? yes
My App dnot start, White screen 
Iam reinstal plugin now, post results 
Thanks

**Comment by Eonassis** [comment]
Dear @mleroi 

thank you help-me

in the annex follows the pints of the screens,

I removed and reinstalled the plugin,
I reinstalled the original themes
the problem persists
thanks!

![aperarence](https://user-images.githubusercontent.com/22618048/31022188-670eb45c-a50e-11e7-9e21-97106a925ff2.JPG)
![tremes](https://user-images.githubusercontent.com/22618048/31022189-6721209c-a50e-11e7-815c-ad913dc74db7.JPG)
![tremes2](https://user-images.githubusercontent.com/22618048/31022190-6729f29e-a50e-11e7-8e0f-aee0793c5fff.JPG)

**Comment by mleroi** [comment]
The #331 is now fixed, which should solve your problem.
The fix will be embedded in next WP-AppKit version (1.2) that will be released in a few weeks.
In the meantime you can download the fixed version of WP-AppKit from the development branch:
To install it:
- download the zip from https://github.com/uncatcrea/wp-appkit/tree/development.
- extract the zip in a temporary folder
- remove your current /plugins/wp-appkit folder
- copy the zip's "wp-appkit" folder into your /plugins folder

**Comment by Eonassis** [comment]
@mleroi 
Thank you for your help.

the error stopped appearing on the screen, but now do not load the other theme

I already reinstalled the default themes

and I downloaded the q-android and uploaded it again, but I can not select it.
when I select and click on save automatically back to q-android

another problem that I identified and config.js, it is as follows:

/* Wp AppKit simulator config.js */
define( function ( require ) {

	"use strict";

	return {
		app_slug : 'uninews-teste',
		wp_ws_url : 'http://uninews.com.br/wp-appkit-api/uninews-teste',
		wp_url : 'http://uninews.com.br',
		theme : 'q',
		version : '1.0',
		app_title : 'uninews2',
		app_platform : 'android',
		gmt_offset : 0,
		debug_mode : 'off',
		auth_key : '254cd7f6cf91818e54082fa8303a8517e18e2096a1554c19a8d9376dea736817',
		options : {"refresh_interval":0},
		theme_settings : [],
		addons : []
	};

});

note that the "theme: 'q',", the correct one I think would be q-android, I also can not preview in broser

**Comment by Eonassis** [comment]
preview send mensage 

WP AppKit error : config.js not found.
Please check that : 
- you are connected to your WordPress back office,
- WordPress permalinks are activated

**Comment by Eonassis** [comment]
new theme d'not select, 

select and save new theme, back to q Andriod

**Comment by mleroi** [comment]
Hi @Eonassis this theme issue is not related to the previous "warning" problem.
So I'm closing here and we can continue about the theme issue here: https://github.com/uncatcrea/wp-appkit/issues/335

**Comment by Eonassis** [comment]
ok 
thank you, help-me!
