### ISSUE TITLE
My app and preview dnot show images the posts

### ISSUE THREAD

**Issue by Eonassis** [uncatcrea/wp-appkit#336]
hi,

my app and my preview in the web broser don't show images the WP posts

help-me!

@mleroi 

![image](https://user-images.githubusercontent.com/22618048/31107026-0963da70-a7c6-11e7-822b-742118284907.png)

**Comment by mleroi** [comment]
Hi @Eonassis, thanks for pointing that out, this is solved with the following fix: https://github.com/uncatcrea/wp-appkit/issues/337
To retrieve the fix you can download and install the last version of the [development branch](https://github.com/uncatcrea/wp-appkit/tree/development).

**Comment by Eonassis** [comment]
solve! thank you! excelent suport @mleroi, congratulations!!!
