### ISSUE TITLE
Warning on post's thumbnail array

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#337]
Non initialized array key [here](https://github.com/uncatcrea/wp-appkit/blob/master/wp-appkit/lib/components/components-utils.php#L64) leads to a warning on PHP7.1.
This leads to featured images not showing in app, as pointed out [here](https://github.com/uncatcrea/wp-appkit/issues/336).

**Comment by Eonassis** [comment]
solve! thank you! excelent suport @mleroi, congratulations!!!
