### ISSUE TITLE
Create tutorial push notifications in android

### ISSUE THREAD

**Issue by Eonassis** [uncatcrea/wp-appkit#338]
Dear,

I'm trying the days to no avail, I'd like to implement push notifications in the app app.

I would like to have a tutotrial, manual or way to make push notifications in the appkit

this may seem like an easy task for the appkit team, but it is too difficult to implement by anyone using appkit.

help-me!!

**Comment by Eonassis** [comment]
@mleroi @blupu @lpointet When you have a little time, please help me.

thank you!

**Comment by blupu** [comment]
Hi @Eonassis, it is certainly not a trivial task. You can use a Cordova plugin such as this one: https://github.com/phonegap/phonegap-plugin-push.

On our side, we favor solutions such as Pushwoosh or One Signal.

Unfortunatly, it's way beyond the scope of a tutorial as it involves configuration for iOS, Android and in the app itself. [This is why we have released add-ons](https://uncategorized-creations.com/3954/first-wp-appkit-add-ons-available/).

You can have a look on the Pushwoosh add-on as it may correspond to your need: https://uncategorized-creations.com/downloads/pushwoosh-wp-appkit/.

Don't hesitate to read the documentation: https://uncategorized-creations.com/wp-appkit/doc/addons/pushwoosh/.
