### ISSUE TITLE
Wp Appkit issue

### ISSUE THREAD

**Issue by zebarehman** [uncatcrea/wp-appkit#340]
I've added wp appkit files to wp content, created a sample application but when I preview the files it gives me a dead screen and shows the following errors on console

Failed to load resource: the server responded with a status of 404 (Not Found):8888/wordpress/wp-content/plugins/wp-appkit/app/themes//head.html?wpak_app_id=hyatt-place&bust=1509613195843 

Uncaught Error: vendor/../themes//head.html?wpak_app_id=hyatt-place&bust=1509613195843 HTTP status: 404
    at XMLHttpRequest.xhr.onreadystatechange : require.js:8 (text.js?wpak_app_id=hyatt-place&bust=1509613195843:291)

**Comment by lpointet** [comment]
Hello,
It seems you didn't select any theme for your application, did you?
Regards,
Lionel

**Comment by blupu** [comment]
Not active - closing.
