### ISSUE TITLE
Parse error: syntax error, unexpected end of file...

### ISSUE THREAD

**Issue by steveboj** [uncatcrea/wp-appkit#341]
When I click the 'Preview' button I just see a white screen and get the following error in my php error log:

Parse error: syntax error, unexpected end of file in /home/myacount/mysite.com/wp-content/themes-wp-appkit/q-ios/php/add-custom-data.php on line 32

I also see that same error when I click the 'View config.js' or 'View config.xml' links.

This is on a new fresh Wordpress install with permalinks activated and no other plugins running, so I'm assuming it has something to do with my server setup?

**Comment by lpointet** [comment]
Hi,
This is probably due to the fact there is the closing tag at the end of this file (`?>`).
Could you please remove it and retry to see if it's better?

**Comment by steveboj** [comment]
Hi
Thanks for the suggestion, but removing the closing php tag hasn't changed anything. Is there anything else you can think of that I can try?

**Comment by lpointet** [comment]
Could you please send us the error you have now without the last line in the file?

**Comment by steveboj** [comment]
The error is exactly same, but now says "line 30" instead of 32.

`Parse error: syntax error, unexpected end of file in /home/myacount/mysite.com/wp-content/themes-wp-appkit/q-ios/php/add-custom-data.php on line 30`

**Comment by steveboj** [comment]
The error is still the same, but it now says "line 30" instead of 32.

`Parse error: syntax error, unexpected end of file in /home/myacount/mysite.com/wp-content/themes-wp-appkit/q-ios/php/add-custom-data.php on line 30`

**Comment by mleroi** [comment]
Hi! Can you please try to remove all the php comments (lines starting with "//") inside the _wpak_add_custom_data_ function of the _add-custom-data.php_ file ?
One of our previous user was having the same problem some time ago and I'm not sure why but it apparently solved the problem for him.

**Comment by steveboj** [comment]
Aha, yes, that's solved it!

It's the <%= xxx %> tags inside the comments that are causing the problem. Remove them and it works fine.

**Comment by mleroi** [comment]
Thanks for the feedback, we thought it could be those tags that messed up with PHP parsing indeed... even if it's surprising as there's inside PHP comments...
This is probably due to a specific PHP config setting somewhere as this happens very rarely.
Anyway we will [fix that](https://github.com/uncatcrea/q-ios/issues/9) in next q-ios theme version. 
Thanks for helping narrowing this down and have fun with WP-AppKit!

**Comment by larsonreever** [comment]
This is probably due to a specific PHP config setting here's a very detailed tutorial on this, i liked the way they explained it - https://secure.wphackedhelp.com/blog/fix-parse-error-syntax-error-unexpected-wordpress/
