### ISSUE TITLE
PWA's how-to

### ISSUE THREAD

**Issue by haemeulrich** [uncatcrea/wp-appkit#353]
I would loke to test the PWA part. How do I have to create a PWA? Is there a special URL?

**Comment by blupu** [comment]
Hi, you will find the PWA enabled version of WP-AppKit on the [development-pwa branch](https://github.com/uncatcrea/wp-appkit/tree/development-pwa) of this repo.

My advice would be to setup a fresh install of WordPress with this version of the plugin and play a little bit with it :-)

If you have any questions or need help, don't hesitate.

Have fun.

**Comment by haemeulrich** [comment]
Wow, thank you! Looking forward!

**Comment by mleroi** [comment]
PWAs are now natively supported in WP-AppKit version 1.5 :)
