### ISSUE TITLE
Connection Error: App Installed

### ISSUE THREAD

**Issue by victorbrites** [uncatcrea/wp-appkit#357]
When the application is installed the message is displayed: Remote connection to the site failed
In the browser it is working normally

https://queroestagio.com/wp-content/plugins/wp-appkit/app/config.xml?wpak_app_id=quero-estagio-android
https://queroestagio.com/wp-content/plugins/wp-appkit/app/config.js?wpak_app_id=quero-estagio-android

Can you help?

**Comment by mleroi** [comment]
Hi @victorbrites,
Different reasons can lead to this kind of problem. 
Can you please reach us at support@uncategorized-creations.com so that we can find what's wrong in your case? If something useful for other users comes out, we'll post it back here.
Thanks

**Comment by blupu** [comment]
Inactive question - closing.
