### ISSUE TITLE
I am having problems with IOS approval

### ISSUE THREAD

**Issue by Donald3d** [uncatcrea/wp-appkit#363]
Hi guys , each time I submit the IOS app , it keeps getting disapproved .With reasons like "content the same as that in website", "not a enough content etc"
What can I do to get IOS approval of my app, please help guys

**Comment by blupu** [comment]
To be validated by Apple, your app must add value comparing to your website. For example: notifications, specific content...

**Comment by Donald3d** [comment]
Ok.Thanks 
I would try it 
Please kindly create a tutorial for Onesignal, I would really appreciate.
Thanks so far to you and your team for your hard work

**Comment by blupu** [comment]
Thank you.
