### ISSUE TITLE
Error unexpected '[' on active plugin

### ISSUE THREAD

**Issue by alefemafra** [uncatcrea/wp-appkit#365]
Parse error: syntax error, unexpected '[' in /home/alefecom/vozdoque.com.br/wp-content/plugins/wp-appkit/lib/web-services/web-service-context.php on line 38

**Comment by mleroi** [comment]
Hi @alefemafra, are you running a PHP version < 5.4 (where brackets definition for arrays was not yet supported) ?

**Comment by alefemafra** [comment]
hi @mleroi , thanks for your information, solved my problems.
