### ISSUE TITLE
Wrong security token

### ISSUE THREAD

**Issue by cesarino80** [uncatcrea/wp-appkit#367]
Hi,

I'm using WP appkit on Wordpress 4.9.5 and I have this error when I try the preview: 

App error event [synchro:ws-return-error] Web service "synchronization" returned an error : [Wrong security token] 
{type: "web-service", where: "app::syncWebService", message: "Web service "synchronization" returned an error : [Wrong security token]", data: {…}}
data
:
{result: {…}}
message
:
"Web service "synchronization" returned an error : [Wrong security token]"
type
:
"web-service"
where
:
"app::syncWebService"

I can't understand the problem, Config.xml and "Show Me Webservice Data" are working well.

Thanks for your support

Felix

**Comment by cesarino80** [comment]
Solved: was a wrong server time setting.

**Comment by mleroi** [comment]
Ok, thanks @cesarino80 for your feedback on this issue.
