### ISSUE TITLE
Compatibility with WPML plugin

### ISSUE THREAD

**Issue by eskaigualker** [uncatcrea/wp-appkit#369]
Is it possible to get both plugins working?

Thank you

**Comment by mleroi** [comment]
Hi,

Yes WP-AppKit allows to customize post data sent to apps, so it is possible to send translated posts to your app. It will require some development though (using WP-AppKit and WPML hooks and apis) to be able to retrieve and send translated posts to the app.

The first thing is to define what you want to achieve exactly.
There are 2 ways of addressing this problematic with WP-AppKit:
- When you switch to a language (e.g. english) in your app (via a language switcher in menu), then all app content is refreshed to english by retrieving english version only of posts from server. This means you have one language at a time in the app. Then to re-switch language you have to access network to refresh app content to another language.
- All posts versions are downloaded into the app each time the app synchronizes with server. This way the app "knows" all languages of each post without needing to access network to switch language. Then you can filter your post lists and singles display dynamically on app side to show only posts that are in the currently chosen language.

Note that solution 2 can be seducing but the downside is that depending on the number of posts you need to display and the number of languages, it can lead to performance issues, and it is significantly trickier to implement.

Depending on what you want to achieve exactly we can give you implementation hints.
