### ISSUE TITLE
Great Project it will be nice to add Save Post option into each Post

### ISSUE THREAD

**Issue by talebettoo** [uncatcrea/wp-appkit#372]

**Comment by blupu** [comment]
Could you provide more details please?

**Comment by talebettoo** [comment]
i mean make an option that allows the users to save the post or bookmarked it to review it later ,
thanks.

**Comment by blupu** [comment]
Hi @talebettoo we plan to release an addon allowing to use offline favorites in apps. Don't hesitate to subscribe to our newsletter to get notified when it'll be available. https://uncategorized-creations.com/
