### ISSUE TITLE
Is pinch and zoom possible?

### ISSUE THREAD

**Issue by eskaigualker** [uncatcrea/wp-appkit#380]
Not directly related wit wp-appkit, but I have tried many plugins to zoom in the images in the app.
None worked. Somebody know if it is possible with Phonegap?

Thank you

**Comment by mleroi** [comment]
Hi, we have this tutorial implementing image zooming using PhotoSwipe: https://uncategorized-creations.com/3114/add-image-zooming-to-your-app-with-photoswipe/
Is that what you're looking for?

**Comment by eskaigualker** [comment]
I'm sorry, what a shame. Actually, I followed this tutorial a couple of years ago, but I do not remember anymore why I rejected it.
Next week I'll try again and I'll let you know, thank you very much!

**Comment by mleroi** [comment]
No problem, don't hesitate for any question about the tutorial

**Comment by eskaigualker** [comment]
It worked like a charm.
Thanks!!

**Comment by mleroi** [comment]
Great!
