### ISSUE TITLE
internal-anchor links

### ISSUE THREAD

**Issue by eskaigualker** [uncatcrea/wp-appkit#386]
I cannot get something as simple as this to work.
For some reason I always end up in the default route.

 I am using q-theme as is.

```
<div id="fragment">bla bla bla</div>
<a href="#fragment">go up</a>
```

Thank you.

**Comment by mleroi** [comment]
Hi @eskaigualker,
Here is a short tutorial about how to solve this problem: 
https://uncategorized-creations.com/4839/handle-internal-links/
Hope this helps,
Regards

**Comment by eskaigualker** [comment]
Thank you very much!
I missed the "closest" app-screen" part.
