### ISSUE TITLE
Help buttons in metaboxes

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#55]
**UI problem:** help texts clutters the edit panel metaboxes

**Proposed solution**:
* Display a _Help me_ link on the upper right corner of each metaboxe content area (below title)
* Clicking this _Help me_ link displays help texts
* When clicked the _Help me_ label changes to _Hide help texts_
* All help texts should be: font-size:13px;font-style:italic;color:#444

_Space for hidden texts is not reserved to avoid strange white gaps between inputs. It implies that when texts are shown, the height of the metabox grows_

**Optional:**
* When focus is set to a text input
* If help texts are displayed
* Its help text should be highlighted in yellow (let's try background-color:#fffe96;)

![wf-help-me-links---001](https://cloud.githubusercontent.com/assets/6179747/6657286/5483ca14-cb47-11e4-878f-585a2bbd3a24.png)

_Based on https://github.com/lpointet/wp-app-kit/tree/feature_ui fork_

**Comment by lpointet** [comment]
Little thought: WordPress is providing a way to display some help related to the current screen. You can see it on top of each screen, near "Screen Options". This link expands a panel with potentially some "tabs" and why not additional links to online documentation.
Could we use it to lighten a bit the UI?

**Comment by blupu** [comment]
As discussed during weekly meeting: next step is to have a list of all texts per metaboxes.

**Comment by lpointet** [comment]
First, I'll develop the toggle link feature, I open a new issue to define help texts.
