### ISSUE TITLE
PhoneGap Build metabox - mandatory fields

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#56]
We need to define which fields from "PhoneGap Build" metabox are "mandatory" for the corresponding checklist element to be "OK".
What I propose is the following:
 - application name
 - application id
 - version
 - PhoneGap version

What do you think?

**Comment by mleroi** [comment]
To make a PhoneGap build App compilation and be able to deploy to device, the following fields are required :
- application name
- application id (`com.yourcompany.yourapp`, and for iPhone this ID must be declared in the Apple developer account)
- application version (`0.0.1`)

PhoneGap version is set to last PhoneGap version by PhoneGap Build if not set in config.xml, so if ok with you I think we don't need to consider it as required.

PhoneGap Build reference about config.xml fields :
http://docs.build.phonegap.com/en_US/configuring_basics.md.html#The%20Basics
http://docs.build.phonegap.com/en_US/configuring_preferences.md.html#Preferences

**Comment by lpointet** [comment]
Following our weekly call, here are the fields the user needs to fill in to check the Phonegap point:
* application name
* application id
* application version
* application versionCode
* application description
* application author
* application author website
* application author email
