### ISSUE TITLE
Metaboxes help texts

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#57]
We should define texts that show up in each metabox when the user clicks on the dedicated link.

**Comment by blupu** [comment]
@lpointet I propose that we postpone help texts review to the 0.4.

**Comment by lpointet** [comment]
@blupu Could we include this into 0.5?

**Comment by lpointet** [comment]
@blupu are proposed help texts good to go? I can include them so that we could iterate directly on dev version during 0.6 development?

**Comment by lpointet** [comment]
Discussed today: OK for integrating these texts.

**Comment by lpointet** [comment]
https://github.com/uncatcrea/wp-appkit/commit/5f90908365e3fa6516e1881fb87bd90de859a528 updates French translations regarding help texts, everything's done.
