### ISSUE TITLE
Platform specific fields

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#58]
We should dynamically show/hide fields that we know are platform-specific when the user chooses one of the available platforms (iOS / Android).

**Comment by blupu** [comment]
Could be nice to also have this mechanism for metabox too (eg. an iOS specific metabox to manage splashscreen duration and options).

**Comment by lpointet** [comment]
One thing to know about platform specific metaboxes: they need to have some CSS classes added to their main div tag. This can be achieved by filtering in the following way:
```php
add_filter( 'postbox_classes_{$screen_id}_{$metabox_id}', 'callback_method' );

function callback_method( $classes ) {
	$classes[] = 'platform-specific'; // This is required for all platform specific metaboxes
	$classes[] = 'ios'; // This is the target platform identifier (ios / android)

	return $classes;
}
```
