### ISSUE TITLE
Thoughts about the new publish metabox

### ISSUE THREAD

**Issue by mleroi** [uncatcrea/wp-appkit#63]
As discussed with Lionel, here are some things I said to myself on the publish metabox when discovering the new UI (Lionel feature-ui branch):

- the "Export" button appears as the first cickable element in the box (up left corner) whereas it is the last thing you will do in the app building process. 

- I feel like we don't really know what will happen when we click "Export". Would "Phonegap Export" be more meaningful? But we also know that this export can be a simple "Web app export"...

- So maybe a "help me" link would be nice in this Publish metabox too? To explain the Preview and Export buttons, and to tell a word about the checklist role. Or a slight change in labels and real "check" icons in the check list can do the trick?

**Comment by blupu** [comment]
_I try to wrap head around that topic :-)_

First, I think that if we need a _help me_ link in that metabox, we're missing something :-\

My first thought is about the Metabox title: it doesn't say what is its purpose.

*What about: My Project Advancement?*

Then we should be clear about _unlocking_ the project by completing all steps.

* We may add a text before the bullet list: _Steps to complete your app_*
* Then we can add a greyed text until all steps are not completed: Project not complete*
* When all steps are green, we change the text to: Project ready!*
* Export and Preview buttons are unlocked when all steps are completed
* Ideally I would place them under the checklist
* Save may stay where it is - maybe we should change its label to: Save Project (see below)

A more broader issue is that we talk of apps as if all is done in WordPress. In fact, we're kind of preparing the app in WordPress to be able to compile it. What we deliver is the App's source ready to be compiled. We could switch from application to application's project (even it sounds a bit complicated).

_Make sense?_

**Comment by lpointet** [comment]
If you lock the preview button until all steps are done, you're blocking user from developing/developing/testing apps without having entered all PhoneGap config data, which is too bad I think.
My thought about that was to have three status for these steps:
1. red => not done and this is blocking you from exporting / previewing your app
2. orange => not done, but not blocking, just be aware that the project isn't complete for a real compilation
3. green => done, you're ready

Of course, colours are an example, could be something else.

**Comment by blupu** [comment]
Good point. I would not introduce a new color but rather have a third phrase like: You can now preview your app in the browser (and unlock the button at the same time).

So we might have:
- Complete steps to be able to preview and export
- You can now preview your app in the browser - one more step to export -> unlock Preview button
- Project sources available for compilation -> unlock Export button

I believe that the button states have to be clearly different so that the user can understand that he/she has unlocked something.

_Make sense?_

**Comment by lpointet** [comment]
Seems a bit constraining to me, to be honest. Mathieu was saying during our skype call that he didn't want to block the "Export" feature either, because we may want to export the app even if it's not to compile it.
What do you think?

**Comment by blupu** [comment]
Ah... If so, blocking buttons is not a good idea ;-)

So we should abandon blocking buttons. Or we may keep goal phrases only to inform user:
* Complete steps to preview and export
* You can preview but one more step to export
* Ready to preview and export

BTW I believe that PhoneGap Export label is a good idea (is this PhoneGap or PhoneGap Build export?).

**Comment by mleroi** [comment]
As I see it, for now we have 2 kinds of export :
- *"Web App Export"*, that we can export even if PhoneGap fields are not set. This is the one Lionel was talking about, I think we all agree that the "Web app" feature of WP AppKit (copy export to a server, run in browser, no PhoneGap lib required) is a very interesting one. 
I think that as soon as we can preview we can export as Web App.
- *"PhoneGap Build Export"* : you have to set Phonegap fields to make a PhoneGap Build Export.

And we will certainly add a "PhoneGap CLI Export" in the futur (config.xml is different than for PhoneGap Build).

**Comment by lpointet** [comment]
Following our weekly meeting:
Publish Metabox
* Splitted in 2 metaboxes: Save & Preview and My Project
* Save & Preview elements: Preview button, Last saved date and time, Move to trash link, Save button
* Ideally the Save label is never changed for Update
* My Project elements: checklist, Export button (at the bottom)
* Export button is preceded by the PhoneGap Build label
* This label might be turned to a dropdown listbox if several export modes are supported
