### ISSUE TITLE
Fatal Error on Plugin Activation

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#73]
- Download and install 0.3 beta (dev branch)
- Activate plugin

x Fatal Error is raised

Additional info:
* Error message: *Fatal error: Can't use function return value in write context in /home/diplok/www/tests/wp-content/plugins/wp-appkit/lib/apps/apps.php on line 251*
* Error happens with PHP Version 5.3.29

**Comment by lpointet** [comment]
I checked the whole plugin PHP codebase, nothing found with "empty(" and a function call after it. We seems to be good with it.
