### ISSUE TITLE
Windows zip creation

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#74]
Creating a PhoneGap export zip on a Windows WP install doesn't work with PhonGap Build as file paths are exported with backslashes ("\") and not slashes ("/").
PhoneGap Build returns the following error: Error - Invalid filename: themes/bootstrap\archive-favorites.html 

I remember I have seen a piece of WordPress core code that is doing some kind of magic with Windows path, I'll try to remember where: we should use the same one I guess :).

**Comment by blupu** [comment]
@lpointet Do we close that issue? (I didn't verify it yet.)
