### ISSUE TITLE
Access rights problem when trying uploading a theme

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#75]
- Add an application
- Click on the _Upload themes_ link in the _Appearance_ metabox

:( "Vous n’avez pas les droits suffisants pour accéder à cette page." is displayed (in French as it tries to access another WordPress install, see below).

It tries to access to http://somedomain/wp-admin/admin.php?page=wpak_bo_upload_themes.

Note that if I access _Upload Themes_, I don't have the problem.

It accesses http://somedomain/**tests**/wp-admin/admin.php?page=wpak_bo_upload_themes.

I believe the _tests_ subfolder is causing the problem.

**Comment by lpointet** [comment]
Wow, that's weird. Can you try editing

**Comment by lpointet** [comment]
Just tried to reproduce this, no problem for me. Do you have some other plugins that could mess around?

**Comment by blupu** [comment]
admin_url() replacing solves the problem.
