### ISSUE TITLE
great project guys! i have question.

### ISSUE THREAD

**Issue by foxpcteam** [uncatcrea/wp-appkit#83]
Hi,
great project guys! good luck!
i have question.
i using wordpress multisite. i want to create simple app that will allow users to login true app and then to show the login user (administrator) some statistics from his site.

like:
comments count
google analytics
info from custom post types
info from woocommerce using api
info form gravity form using api
and etc...

the question is if this possibly using this appkit?

**Comment by blupu** [comment]
Hi,

* First WP-AppKit is compatible with multisite.
* Regarding _login_, I assume that you want  to use the WordPress user management (?). If so,we don't support authentication at the moment. (It's definitely on our roadmap).
* Custom Post Types are natively supported in WP-AppKit.
* WooCommerce and Gravity Forms support is possible but you'll have to use our API to support them.
* It is the same for Google Analytics, except of course, you'll have to do all the work as it is an external source (ie. not WordPress).

So I would say that it is possible if you build the authentication and do a good work of customization.

Regards.
