### ISSUE TITLE
Export zip creation with PHP >= 5.2.8

### ISSUE THREAD

**Issue by lpointet** [uncatcrea/wp-appkit#88]
PhoneGap build export zip creation doesn't work with PHP 5.2.8 and later, as ZipArchive::OVERWRITE constant isn't sufficient for ZipArchive::open to create a new file.
Plus, a Warning is showing: "ZipArchive::addEmptyDir(): Invalid or unitialized Zip object in /lib/apps/build.php on line 254".

**Comment by blupu** [comment]
Fixed in 0.3.1.
